export const FIXTURES = {
  'e-commerce': {
    name: 'E-Commerce Product (Offers, Reviews, Brand)',
    url: 'https://example.com/products/wireless-headphones',
    canonical: 'https://example.com/products/wireless-headphones',
    entities: [
      {
        id: 'https://example.com/products/wireless-headphones#brand',
        types: ['Brand', 'Organization'],
        format: 'jsonld',
        sourceIndex: 0,
        data: {
          '@context': 'https://schema.org',
          '@type': 'Brand',
          '@id': 'https://example.com/products/wireless-headphones#brand',
          name: 'SoundWave Audio',
          url: 'https://example.com',
          sameAs: 'https://wikidata.org/wiki/Q99999',
        },
      },
      {
        id: 'https://example.com/products/wireless-headphones#product',
        types: ['Product'],
        format: 'jsonld',
        sourceIndex: 0,
        data: {
          '@context': 'https://schema.org',
          '@type': 'Product',
          '@id': 'https://example.com/products/wireless-headphones#product',
          name: 'SoundWave Pro Wireless ANC Headphones',
          description: 'High fidelity active noise cancelling Bluetooth headphones with 40h battery life.',
          image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
          sku: 'SW-ANC-400',
          mpn: '920-008001',
          brand: { '@id': 'https://example.com/products/wireless-headphones#brand' },
          aggregateRating: {
            '@type': 'AggregateRating',
            ratingValue: '4.8',
            reviewCount: '342',
            bestRating: '5',
            worstRating: '1',
          },
          offers: {
            '@type': 'Offer',
            price: '249.99',
            priceCurrency: 'USD',
            availability: 'https://schema.org/InStock',
            itemCondition: 'https://schema.org/NewCondition',
            priceValidUntil: '2026-12-31',
            seller: { '@id': 'https://example.com/products/wireless-headphones#brand' },
          },
        },
      },
    ],
  },
  article: {
    name: 'Multi-Author Article & Publisher Graph',
    url: 'https://example.com/news/structured-data-2026',
    canonical: 'https://example.com/news/structured-data-2026',
    entities: [
      {
        id: 'https://example.com/#publisher',
        types: ['NewsMediaOrganization', 'Organization'],
        format: 'jsonld',
        sourceIndex: 0,
        data: {
          '@context': 'https://schema.org',
          '@type': 'NewsMediaOrganization',
          '@id': 'https://example.com/#publisher',
          name: 'Tech Chronicle',
          url: 'https://example.com',
          logo: {
            '@type': 'ImageObject',
            url: 'https://example.com/logo.png',
            width: '600',
            height: '60',
          },
          sameAs: ['https://twitter.com/techchronicle', 'https://wikidata.org/wiki/Q11111'],
        },
      },
      {
        id: 'https://example.com/#author-alice',
        types: ['Person'],
        format: 'jsonld',
        sourceIndex: 0,
        data: {
          '@context': 'https://schema.org',
          '@type': 'Person',
          '@id': 'https://example.com/#author-alice',
          name: 'Alice Johnson',
          jobTitle: 'Senior Tech Editor',
          worksFor: { '@id': 'https://example.com/#publisher' },
          sameAs: 'https://twitter.com/alicejohnson',
        },
      },
      {
        id: 'https://example.com/news/structured-data-2026#article',
        types: ['NewsArticle', 'Article'],
        format: 'jsonld',
        sourceIndex: 0,
        data: {
          '@context': 'https://schema.org',
          '@type': 'NewsArticle',
          '@id': 'https://example.com/news/structured-data-2026#article',
          headline: 'How Schema.org and AI Search Engines Reshaped the Web in 2026',
          datePublished: '2026-08-20T08:00:00+02:00',
          dateModified: '2026-08-26T14:30:00+02:00',
          image: ['https://images.unsplash.com/photo-1518770660439-4636190af475?w=600'],
          author: [{ '@id': 'https://example.com/#author-alice' }],
          publisher: { '@id': 'https://example.com/#publisher' },
          mainEntityOfPage: 'https://example.com/news/structured-data-2026',
        },
      },
    ],
  },
  restaurant: {
    name: 'LocalBusiness & Restaurant (Menu, Geo, Hours)',
    url: 'https://example.com/bistro',
    canonical: 'https://example.com/bistro',
    entities: [
      {
        id: 'https://example.com/bistro#restaurant',
        types: ['Restaurant', 'LocalBusiness', 'FoodEstablishment'],
        format: 'jsonld',
        sourceIndex: 0,
        data: {
          '@context': 'https://schema.org',
          '@type': 'Restaurant',
          '@id': 'https://example.com/bistro#restaurant',
          name: 'Le Bistro Botanique',
          image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=500',
          telephone: '+1-415-555-0199',
          servesCuisine: ['French', 'Contemporary Vegetarian'],
          priceRange: '$$$',
          address: {
            '@type': 'PostalAddress',
            streetAddress: '450 Hayes St',
            addressLocality: 'San Francisco',
            addressRegion: 'CA',
            postalCode: '94102',
            addressCountry: 'US',
          },
          geo: {
            '@type': 'GeoCoordinates',
            latitude: 37.7765,
            longitude: -122.4242,
          },
          aggregateRating: {
            '@type': 'AggregateRating',
            ratingValue: '4.9',
            reviewCount: '488',
          },
          hasMenu: 'https://example.com/bistro/menu',
        },
      },
    ],
  },
  deprecated: {
    name: 'Deprecated Schema (HowTo / SpecialAnnouncement)',
    url: 'https://example.com/how-to-fix',
    canonical: 'https://example.com/how-to-fix',
    entities: [
      {
        id: 'https://example.com/how-to-fix#howto',
        types: ['HowTo'],
        format: 'jsonld',
        sourceIndex: 0,
        data: {
          '@context': 'https://schema.org',
          '@type': 'HowTo',
          name: 'How to replace a bicycle tire',
          step: [
            { '@type': 'HowToStep', text: 'Deflate the inner tube completely.' },
            { '@type': 'HowToStep', text: 'Use tire levers to remove tire bead.' },
          ],
        },
      },
    ],
  },
};
