/* generated by scripts/bundle.mjs — do not edit by hand */
(function (global) {
/**
 * Page-context extraction. Self-contained — no imports, no extension APIs.
 * @file
 */

/**
 * Extract schema markup and page metadata from the current document.
 * Must run inside the inspected page via chrome.devtools.inspectedWindow.eval.
 * @returns {import('./types.js').PageSnapshot}
 */
function extractPageSchema() {
  const MAX_JSONLD_BLOCKS = 100;
  const MAX_JSONLD_CHARS = 500_000;
  const MAX_MARKUP_NODES = 500;
  const MAX_NESTING = 50;
  const MAX_TEXT_CHARS = 100_000;

  /** @param {Element} el */
  function buildSelector(el) {
    if (el.id) {
      return `#${CSS.escape(el.id)}`;
    }
    const parts = [];
    let node = el;
    let depth = 0;
    while (node && node.nodeType === Node.ELEMENT_NODE && node !== document.documentElement && depth++ < MAX_NESTING) {
      if (node.id) {
        parts.unshift(`#${CSS.escape(node.id)}`);
        break;
      }
      let part = node.tagName.toLowerCase();
      if (node.className && typeof node.className === 'string') {
        const cls = node.className.trim().split(/\s+/).filter(Boolean).slice(0, 2);
        if (cls.length) part += '.' + cls.map((c) => CSS.escape(c)).join('.');
      }
      const parent = node.parentElement;
      if (parent) {
        const siblings = Array.from(parent.children).filter((c) => c.tagName === node.tagName);
        if (siblings.length > 1) {
          const idx = siblings.indexOf(node) + 1;
          part += `:nth-of-type(${idx})`;
        }
      }
      parts.unshift(part);
      node = parent;
    }
    return parts.join(' > ');
  }

  /** @param {Element} el */
  function isJsonLdScript(el) {
    if (el.tagName !== 'SCRIPT') return false;
    const type = (el.getAttribute('type') ?? '').split(';', 1)[0].trim().toLowerCase();
    return type === 'application/ld+json';
  }

  /**
   * @param {Record<string, unknown>} props
   * @param {string} names
   * @param {unknown} value
   */
  function addProperties(props, names, value) {
    for (const name of names.split(/\s+/).filter(Boolean)) {
      if (props[name] === undefined) {
        props[name] = value;
      } else if (Array.isArray(props[name])) {
        /** @type {unknown[]} */ (props[name]).push(value);
      } else {
        props[name] = [props[name], value];
      }
    }
  }

  /**
   * @param {string} raw
   * @returns {{parsed: unknown|null, parseError: {message: string, line?: number, column?: number}|null}}
   */
  function parseJsonLd(raw) {
    const trimmed = raw.trim();
    if (!trimmed) {
      return { parsed: null, parseError: { message: 'Empty JSON-LD block' } };
    }
    try {
      return { parsed: JSON.parse(trimmed), parseError: null };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      const posMatch = message.match(/position\s+(\d+)/i);
      let line;
      let column;
      if (posMatch) {
        const pos = Number(posMatch[1]);
        let col = 1;
        let ln = 1;
        for (let i = 0; i < pos && i < trimmed.length; i++) {
          if (trimmed[i] === '\n') {
            ln++;
            col = 1;
          } else {
            col++;
          }
        }
        line = ln;
        column = col;
      }
      return { parsed: null, parseError: { message, line, column } };
    }
  }

  /**
   * @param {Element} scope
   * @returns {Record<string, unknown>}
   */
  function extractMicrodataProps(scope, depth = 0) {
    const props = /** @type {Record<string, unknown>} */ ({});
    /** @type {Array<{el: Element; root: Element}>} */
    const propEls = [];
    const seen = new Set();

    addPropertyRoot(scope, false);
    for (const id of (scope.getAttribute('itemref') ?? '').split(/\s+/).filter(Boolean)) {
      const ref = document.getElementById(id);
      if (ref) addPropertyRoot(ref, true);
    }

    for (const { el, root } of propEls) {
      let between = el.parentElement;
      const stop = root.parentElement;
      while (between && between !== stop) {
        if (between !== scope && between.hasAttribute('itemscope')) break;
        between = between.parentElement;
      }
      if (between && between !== stop) continue;

      const names = el.getAttribute('itemprop');
      if (!names) continue;

      let value;
      if (el.hasAttribute('itemscope')) {
        value = buildMicrodataItem(el, depth + 1);
      } else {
        value = readMicrodataValue(el);
      }
      addProperties(props, names, value);
    }
    return props;

    /**
     * @param {Element} root
     * @param {boolean} includeRoot
     */
    function addPropertyRoot(root, includeRoot) {
      const candidates = [
        ...(includeRoot && root.hasAttribute('itemprop') ? [root] : []),
        ...root.querySelectorAll('[itemprop]'),
      ];
      for (const el of candidates) {
        if (seen.has(el)) continue;
        seen.add(el);
        propEls.push({ el, root });
      }
    }
  }

  /**
   * @param {Element} el
   * @returns {unknown}
   */
  function readMicrodataValue(el) {
    const tag = el.tagName;
    if (tag === 'META') {
      return el.getAttribute('content') ?? el.getAttribute('value') ?? '';
    }
    if (tag === 'LINK' || tag === 'A') {
      return el.getAttribute('href') ?? el.textContent?.trim() ?? '';
    }
    if (tag === 'IMG' || tag === 'AUDIO' || tag === 'EMBED' || tag === 'IFRAME' || tag === 'SOURCE') {
      return el.getAttribute('src') ?? el.getAttribute('data') ?? '';
    }
    if (tag === 'TIME') {
      return el.getAttribute('datetime') ?? el.textContent?.trim() ?? '';
    }
    if (tag === 'OBJECT') {
      return el.getAttribute('data') ?? '';
    }
    return el.textContent?.trim().slice(0, MAX_TEXT_CHARS) ?? '';
  }

  /**
   * @param {Element} el
   * @returns {import('./types.js').MarkupNode}
   */
  function buildMicrodataItem(el, depth = 0) {
    const itemtype = el.getAttribute('itemtype') ?? '';
    const types = itemtype.split(/\s+/).filter(Boolean);
    const type = types.length === 1 ? types[0] : types;
    const properties = depth >= MAX_NESTING ? {} : extractMicrodataProps(el, depth);
    const itemid = el.getAttribute('itemid');
    if (itemid) properties['@id'] = itemid;
    return {
      format: 'microdata',
      type,
      properties,
      selector: buildSelector(el),
    };
  }

  /** @returns {import('./types.js').MarkupNode[]} */
  function extractMicrodata() {
    const items = [];
    const scopes = document.querySelectorAll('[itemscope]');
    for (const el of scopes) {
      // An item is top-level when it is not itself a property of another item.
      if (!el.hasAttribute('itemprop')) {
        items.push(buildMicrodataItem(el));
        if (items.length >= MAX_MARKUP_NODES) break;
      }
    }
    return items;
  }

  /**
   * @param {Element} el
   * @returns {Record<string, unknown>}
   */
  function extractRdfaProps(el, depth = 0) {
    const props = /** @type {Record<string, unknown>} */ ({});
    const propEls = el.querySelectorAll('[property], [rel]');
    for (const propEl of propEls) {
      if (!el.contains(propEl) || propEl === el) continue;
      let between = propEl.parentElement;
      while (between && between !== el) {
        if (between.hasAttribute('typeof')) break;
        between = between.parentElement;
      }
      if (between && between !== el) continue;

      const names = propEl.getAttribute('property') ?? propEl.getAttribute('rel');
      if (!names) continue;
      let value;
      if (propEl.hasAttribute('typeof')) {
        value = buildRdfaNode(propEl, depth + 1);
      } else if (propEl.hasAttribute('content')) {
        value = propEl.getAttribute('content');
      } else if (propEl.tagName === 'A' || propEl.tagName === 'LINK') {
        value = propEl.getAttribute('resource') ?? propEl.getAttribute('href') ?? propEl.textContent?.trim() ?? '';
      } else if (propEl.tagName === 'IMG') {
        value = propEl.getAttribute('src') ?? '';
      } else {
        value = propEl.getAttribute('resource') ?? propEl.getAttribute('href') ?? propEl.textContent?.trim().slice(0, MAX_TEXT_CHARS) ?? '';
      }

      addProperties(
        props,
        names.split(/\s+/).filter(Boolean).map((name) => expandRdfaTerm(name, propEl)).join(' '),
        value,
      );
    }
    return props;
  }

  /**
   * @param {Element} el
   * @returns {import('./types.js').MarkupNode}
   */
  function buildRdfaNode(el, depth = 0) {
    const typeofAttr = el.getAttribute('typeof') ?? '';
    const types = typeofAttr.split(/\s+/).filter(Boolean).map((type) => expandRdfaTerm(type, el));
    const vocab = el.getAttribute('vocab') ?? el.closest('[vocab]')?.getAttribute('vocab') ?? '';
    const resource = el.getAttribute('resource') ?? el.getAttribute('about') ?? el.getAttribute('href') ?? '';
    const properties = depth >= MAX_NESTING ? {} : extractRdfaProps(el, depth);
    if (resource) properties['@id'] = resource;
    if (vocab) properties.vocab = vocab;
    const type = types.length === 1 ? types[0] : types.length ? types : 'Thing';
    return {
      format: 'rdfa',
      type,
      properties,
      selector: buildSelector(el),
    };
  }

  /**
   * Resolve schema.org RDFa terms while leaving unrelated vocabularies intact.
   * @param {string} term
   * @param {Element} el
   */
  function expandRdfaTerm(term, el) {
    const absolute = term.match(/^https?:\/\/schema\.org\/(.+)$/i);
    if (absolute) return absolute[1];
    const compact = term.match(/^([^:]+):(.+)$/);
    if (!compact) return term;
    if (compact[1].toLowerCase() === 'schema') return compact[2];

    const prefixAttr = el.closest('[prefix]')?.getAttribute('prefix') ?? '';
    const declarations = prefixAttr.matchAll(/(?:^|\s)([A-Za-z][\w.-]*):\s+(\S+)/g);
    for (const declaration of declarations) {
      if (declaration[1] === compact[1] && /^https?:\/\/schema\.org\/?$/i.test(declaration[2])) {
        return compact[2];
      }
    }
    return term;
  }

  /** @returns {import('./types.js').MarkupNode[]} */
  function extractRdfa() {
    const items = [];
    const typeEls = document.querySelectorAll('[typeof]');
    for (const el of typeEls) {
      const parentType = el.parentElement?.closest('[typeof]');
      if ((!el.hasAttribute('property') && !el.hasAttribute('rel')) || !parentType) {
        items.push(buildRdfaNode(el));
        if (items.length >= MAX_MARKUP_NODES) break;
      }
    }
    return items;
  }

  /** @returns {import('./types.js').JsonLdBlock[]} */
  function extractJsonLd() {
    const scripts = Array.from(document.querySelectorAll('script[type]')).filter(isJsonLdScript);
    const blocks = [];
    let domIndex = 0;
    for (const script of scripts.slice(0, MAX_JSONLD_BLOCKS)) {
      const fullRaw = script.textContent ?? '';
      const raw = fullRaw.slice(0, MAX_JSONLD_CHARS);
      const result = fullRaw.length > MAX_JSONLD_CHARS
        ? { parsed: null, parseError: { message: `JSON-LD block exceeds ${MAX_JSONLD_CHARS} characters and was skipped.` } }
        : parseJsonLd(raw);
      blocks.push({
        index: blocks.length,
        raw,
        parsed: result.parsed,
        parseError: result.parseError,
        selector: buildSelector(script),
        domIndex,
      });
      domIndex++;
    }
    if (scripts.length > MAX_JSONLD_BLOCKS) {
      blocks.push({
        index: blocks.length,
        raw: '',
        parsed: null,
        parseError: { message: `JSON-LD extraction stopped after ${MAX_JSONLD_BLOCKS} blocks.` },
        selector: 'jsonld:truncated',
      });
    }
    return blocks;
  }

  /** @returns {import('./types.js').AgentSurface} */
  function extractAgentSurface() {
    let hasModelContext = false;
    /** @type {object|null} */
    let modelContext = null;

    let ctx;
    try {
      ctx = document.modelContext;
    } catch {
      ctx = undefined;
    }
    if (ctx && typeof ctx === 'object') {
      hasModelContext = true;
      try {
        const serialized = /** @type {Record<string, unknown>} */ ({});
        const ctxObj = /** @type {Record<string, unknown>} */ (ctx);
        const tools = ctxObj.tools;
        if (Array.isArray(tools)) {
          serialized.tools = tools.slice(0, 50).map((tool) => {
            if (typeof tool !== 'object' || tool === null) return tool;
            const t = /** @type {Record<string, unknown>} */ (tool);
            const out = {};
            for (const key of ['name', 'description', 'inputSchema', 'parameters', 'type']) {
              if (key in t && typeof t[key] !== 'function') out[key] = t[key];
            }
            return out;
          });
        }
        const encoded = JSON.stringify(serialized);
        modelContext = encoded.length <= MAX_JSONLD_CHARS
          ? JSON.parse(encoded)
          : { truncated: true, message: 'Model context metadata exceeds the export limit.' };
      } catch {
        modelContext = null;
      }
    }

    let hasLlmsTxtLink = false;
    const links = document.querySelectorAll('link[rel]');
    for (const link of links) {
      const rel = (link.getAttribute('rel') ?? '').toLowerCase().split(/\s+/);
      const href = link.getAttribute('href') ?? '';
      if (rel.includes('describedby') && /(?:^|\/)llms\.txt(?:[?#]|$)/i.test(href)) {
        hasLlmsTxtLink = true;
        break;
      }
    }
    if (!hasLlmsTxtLink) {
      const anchors = document.querySelectorAll('a[href]');
      for (const a of anchors) {
        if (/(?:^|\/)llms\.txt(?:[?#]|$)/i.test(a.getAttribute('href') ?? '')) {
          hasLlmsTxtLink = true;
          break;
        }
      }
    }

    return { hasModelContext, modelContext, hasLlmsTxtLink };
  }

  const canonicalEl = document.querySelector('link[rel="canonical"]');
  const robotsEl = document.querySelector('meta[name="robots"]');

  return {
    url: location.href,
    title: document.title ?? '',
    canonical: canonicalEl?.getAttribute('href') ?? null,
    robots: robotsEl?.getAttribute('content') ?? null,
    inspectedAt: new Date().toISOString(),
    jsonld: extractJsonLd(),
    microdata: extractMicrodata(),
    rdfa: extractRdfa(),
    agent: extractAgentSurface(),
  };
}

/** Eval source for chrome.devtools.inspectedWindow.eval — returns a JSON string. */
const EXTRACT_SOURCE = `(() => {
  try {
    const data = (${extractPageSchema.toString()})();
    return JSON.stringify(data);
  } catch (err) {
    return JSON.stringify({
      __extractError: err && err.message ? err.message : String(err)
    });
  }
})()`;


/**
 * Google Rich-Result Rule Catalog.
 * Declarative requirements and recommendations based on Google Search Central documentation.
 * @file
 */

/** @typedef {import('../types.js').TypeRule} TypeRule */

/** Schema.org LocalBusiness subtypes supported by Google's Local Business guide. */
const LOCAL_BUSINESS_TYPES = new Set([
  'LocalBusiness', 'AccountingService', 'AnimalShelter', 'Attorney', 'AutomotiveBusiness',
  'Bakery', 'BarOrPub', 'BeautySalon', 'BedAndBreakfast', 'BikeStore', 'BookStore',
  'BowlingAlley', 'Brewery', 'CafeOrCoffeeShop', 'Campground', 'Casino', 'ChildCare',
  'ClothingStore', 'ComputerStore', 'ConvenienceStore', 'DaySpa', 'Dentist',
  'DepartmentStore', 'Distillery', 'DryCleaningOrLaundry', 'Electrician',
  'EmergencyService', 'EmploymentAgency', 'EntertainmentBusiness', 'ExerciseGym',
  'FastFoodRestaurant', 'FinancialService', 'Florist', 'FoodEstablishment',
  'FurnitureStore', 'GardenStore', 'GasStation', 'GeneralContractor', 'GolfCourse',
  'GovernmentOffice', 'GroceryStore', 'HardwareStore', 'HealthAndBeautyBusiness',
  'HealthClub', 'HobbyShop', 'HomeAndConstructionBusiness', 'Hostel', 'Hotel',
  'HVACBusiness', 'IceCreamShop', 'InsuranceAgency', 'InternetCafe', 'JewelryStore',
  'LegalService', 'Library', 'LiquorStore', 'LodgingBusiness', 'Locksmith',
  'MedicalBusiness', 'MensClothingStore', 'MiddleSchool', 'Motel', 'MotorcycleDealer',
  'MovieTheater', 'MovingCompany', 'MusicStore', 'NightClub', 'Notary',
  'OfficeEquipmentStore', 'Optician', 'OutletStore', 'PawnShop', 'PetStore', 'Pharmacy',
  'Plumber', 'PoliceStation', 'PostOffice', 'Preschool', 'ProfessionalService',
  'RadioStation', 'RealEstateAgent', 'RecyclingCenter', 'Resort', 'Restaurant',
  'RoofingContractor', 'SelfStorage', 'ShoeStore', 'ShoppingCenter', 'SkiResort',
  'SportingGoodsStore', 'SportsActivityLocation', 'Store', 'TattooParlor',
  'TelevisionStation', 'TireShop', 'TouristAttraction', 'TouristInformationCenter',
  'ToyStore', 'TravelAgency', 'WholesaleStore',
]);

/** @type {TypeRule[]} */
const RICH_RESULT_RULES = [
  {
    type: 'NewsArticle',
    required: [],
    recommended: ['headline', 'image', 'datePublished', 'dateModified', 'author', 'publisher'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/article',
  },
  {
    type: 'BlogPosting',
    required: [],
    recommended: ['headline', 'image', 'datePublished', 'dateModified', 'author', 'publisher'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/article',
  },
  {
    type: 'Article',
    required: [],
    recommended: ['headline', 'image', 'datePublished', 'dateModified', 'author', 'publisher'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/article',
  },
  {
    type: 'Product',
    required: ['name'],
    recommended: ['image', 'description', 'offers', 'brand', 'sku', 'aggregateRating', 'review'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/product',
  },
  {
    type: 'BreadcrumbList',
    required: ['itemListElement'],
    recommended: [],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/breadcrumb',
  },
  {
    type: 'Event',
    required: ['name', 'startDate', 'location'],
    recommended: ['endDate', 'description', 'image', 'offers', 'performer', 'organizer'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/event',
  },
  {
    type: 'Recipe',
    required: ['name', 'image'],
    recommended: ['author', 'datePublished', 'description', 'recipeIngredient', 'recipeInstructions'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/recipe',
  },
  {
    type: 'JobPosting',
    required: ['title', 'description', 'datePosted', 'hiringOrganization'],
    recommended: ['jobLocation', 'baseSalary', 'employmentType', 'validThrough'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/job-posting',
  },
  {
    type: 'LocalBusiness',
    required: ['name', 'address'],
    recommended: ['image', 'telephone', 'openingHoursSpecification', 'geo', 'url'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/local-business',
  },
  {
    type: 'Organization',
    required: [],
    recommended: ['name', 'url', 'logo', 'sameAs', 'contactPoint'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/organization',
  },
  {
    type: 'VideoObject',
    required: ['name', 'description', 'thumbnailUrl', 'uploadDate'],
    recommended: ['contentUrl', 'duration', 'embedUrl'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/video',
  },
  {
    type: 'SoftwareApplication',
    required: ['name'],
    recommended: ['operatingSystem', 'applicationCategory', 'offers', 'aggregateRating'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/software-app',
  },
  {
    type: 'Course',
    required: ['name', 'description'],
    recommended: ['provider'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/course',
  },
  {
    type: 'Review',
    required: ['itemReviewed', 'reviewRating', 'author'],
    recommended: ['datePublished', 'reviewBody'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/review-snippet',
  },
  {
    type: 'QAPage',
    required: ['mainEntity'],
    recommended: [],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/qapage',
  },
  {
    type: 'ProfilePage',
    required: ['mainEntity'],
    recommended: ['dateCreated', 'dateModified'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/profile-page',
  },
  {
    type: 'DiscussionForumPosting',
    required: ['author', 'datePublished'],
    recommended: ['url', 'comment'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/discussion-forum',
  },
  {
    type: 'SocialMediaPosting',
    required: ['author', 'datePublished'],
    recommended: ['url', 'comment'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/discussion-forum',
  },
  {
    type: 'ItemList',
    required: ['itemListElement'],
    recommended: ['numberOfItems', 'itemListOrder'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/carousel',
  },
  {
    type: 'Dataset',
    required: ['name', 'description'],
    recommended: ['license', 'creator', 'distribution'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/dataset',
  },
  {
    type: 'ProductGroup',
    required: ['name'],
    recommended: ['hasVariant', 'variesBy', 'productGroupID'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/product-variants',
  },
  {
    type: 'MerchantReturnPolicy',
    required: [],
    recommended: [],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/return-policy',
  },
  {
    type: 'OfferShippingDetails',
    required: [],
    recommended: ['shippingRate', 'deliveryTime', 'shippingDestination'],
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/merchant-listing#shipping',
  },
];


/**
 * Google Search & Schema.org lifecycle deprecations.
 * Tracks retired features to prevent false positive quality score penalties.
 * @file
 */

/** Schema types whose Google rich-result feature is no longer supported. */
const DEPRECATED_TYPES = ['HowTo', 'SpecialAnnouncement'];

/** Current Google Search status for FAQPage markup. */
const FAQ_GOOGLE_STATUS = {
  code: 'FAQ_GOOGLE_UNSUPPORTED',
  message:
    'Google Search no longer shows FAQ rich results. These findings check FAQPage structure only and do not imply Google rich-result eligibility.',
  docsUrl: 'https://developers.google.com/search/updates#faq-deprecation',
};


/**
 * Semantic property, ISO format, and syntax check helpers.
 * @file
 */

/** @typedef {import('../types.js').TypeRule} TypeRule */

/**
 * Find the best matching rule for an entity type list.
 * @param {TypeRule[]} catalog
 * @param {string[]} types
 * @returns {TypeRule|null}
 */
function matchRuleInCatalog(catalog, types) {
  for (const rule of catalog) {
    if (types.includes(rule.type)) return rule;
  }
  return null;
}

/**
 * Check if a property exists and contains non-empty value.
 * @param {Record<string, unknown>} data
 * @param {string} prop
 * @returns {boolean}
 */
function hasProperty(data, prop) {
  return hasValue(data[prop]);

  /** @param {unknown} val */
  function hasValue(val, depth = 0) {
    if (depth > 50) return false;
    if (val === undefined || val === null) return false;
    if (typeof val === 'string' && val.trim() === '') return false;
    if (Array.isArray(val)) return val.some((item) => hasValue(item, depth + 1));
    if (typeof val === 'object') {
      return Object.values(/** @type {Record<string, unknown>} */ (val)).some((item) => hasValue(item, depth + 1));
    }
    return true;
  }
}

/**
 * Check if a URL string is relative.
 * @param {unknown} val
 * @returns {boolean}
 */
function isRelativeUrl(val) {
  if (typeof val !== 'string') return false;
  const s = val.trim();
  if (!s) return false;
  if (s.startsWith('//') || s.startsWith('http://') || s.startsWith('https://') || s.startsWith('data:')) {
    return false;
  }
  return !s.includes(':') || s.startsWith('/') || s.startsWith('#') || s.startsWith('?');
}

const URL_PROPS = new Set([
  'url', 'image', 'logo', 'contentUrl', 'thumbnailUrl', 'embedUrl',
  'sameAs', 'item', 'target', 'urlTemplate', 'mainEntityOfPage',
]);

/**
 * Collect URL-like string values from entity data.
 * @param {Record<string, unknown>} data
 * @returns {Array<{path: string, value: string}>}
 */
function collectUrlFields(data) {
  /** @type {Array<{path: string, value: string}>} */
  const found = [];

  visit(data, '', '');
  return found;

  /**
   * @param {unknown} value
   * @param {string} path
   * @param {string} property
   */
  function visit(value, path, property, depth = 0) {
    if (depth > 50) return;
    if (typeof value === 'string') {
      if (URL_PROPS.has(property)) found.push({ path, value });
      return;
    }
    if (Array.isArray(value)) {
      value.forEach((item, i) => visit(item, `${path}[${i}]`, property, depth + 1));
      return;
    }
    if (typeof value !== 'object' || value === null) return;
    for (const [key, child] of Object.entries(/** @type {Record<string, unknown>} */ (value))) {
      const childPath = path ? `${path}.${key}` : key;
      visit(child, childPath, key, depth + 1);
    }
  }
}

const DATE_PROPS = new Set([
  'datePublished', 'dateModified', 'dateCreated', 'datePosted', 'uploadDate',
  'startDate', 'endDate', 'validFrom', 'validThrough', 'priceValidUntil',
]);

const CURRENCY_PROPS = new Set(['priceCurrency', 'currency']);

const ISO8601_RE = /^(\d{4})-(\d{2})-(\d{2})(?:T(\d{2}):(\d{2})(?::(\d{2})(?:\.\d+)?)?(?:Z|([+-])(\d{2}):?(\d{2}))?)?$/;
const ISO4217_RE = /^[A-Z]{3}$/;
const ISO4217_CODES = new Set(
  typeof Intl.supportedValuesOf === 'function'
    ? Intl.supportedValuesOf('currency')
    : ['AUD', 'BRL', 'CAD', 'CHF', 'CNY', 'EUR', 'GBP', 'INR', 'JPY', 'KRW', 'MXN', 'SEK', 'USD'],
);

/**
 * Check if a date string satisfies ISO 8601 calendar date bounds.
 * @param {string} value
 * @returns {boolean}
 */
function isIso8601Date(value) {
  const match = ISO8601_RE.exec(value);
  if (!match) return false;
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const hour = Number(match[4] ?? 0);
  const minute = Number(match[5] ?? 0);
  const second = Number(match[6] ?? 0);
  if (hour > 23 || minute > 59 || second > 59) return false;
  const timezoneHour = Number(match[8] ?? 0);
  const timezoneMinute = Number(match[9] ?? 0);
  if (timezoneHour > 14 || timezoneMinute > 59 || (timezoneHour === 14 && timezoneMinute !== 0)) return false;
  const date = new Date(Date.UTC(year, month - 1, day));
  return date.getUTCFullYear() === year && date.getUTCMonth() === month - 1 && date.getUTCDate() === day;
}

/**
 * Check if a currency code satisfies ISO 4217 (3 uppercase ASCII letters).
 * @param {string} value
 * @returns {boolean}
 */
function isIso4217Currency(value) {
  const code = value.trim();
  return ISO4217_RE.test(code) && ISO4217_CODES.has(code);
}

/**
 * Walk entity data and emit date / currency / rating field checks.
 * @param {Record<string, unknown>} data
 * @returns {Array<{kind: 'date'|'currency'|'rating', path: string, value: unknown}>}
 */
function collectValueChecks(data) {
  /** @type {Array<{kind: 'date'|'currency'|'rating', path: string, value: unknown}>} */
  const found = [];
  visit(data, '');
  return found;

  /**
   * @param {unknown} value
   * @param {string} path
   */
  function visit(value, path, depth = 0) {
    if (depth > 50) return;
    if (Array.isArray(value)) {
      value.forEach((item, i) => visit(item, `${path}[${i}]`, depth + 1));
      return;
    }
    if (typeof value !== 'object' || value === null) return;
    const obj = /** @type {Record<string, unknown>} */ (value);
    for (const [key, child] of Object.entries(obj)) {
      const childPath = path ? `${path}.${key}` : key;
      if (DATE_PROPS.has(key) && (typeof child === 'string' || typeof child === 'number')) {
        found.push({ kind: 'date', path: childPath, value: child });
      } else if (CURRENCY_PROPS.has(key) && typeof child === 'string') {
        found.push({ kind: 'currency', path: childPath, value: child });
      } else if (
        (key === 'reviewRating' || key === 'aggregateRating') &&
        child &&
        typeof child === 'object' &&
        !Array.isArray(child)
      ) {
        found.push({ kind: 'rating', path: childPath, value: child });
      }
      visit(child, childPath, depth + 1);
    }
  }
}


/**
 * Google rich-result and schema.org rule catalog aggregator.
 * Re-exports declarative rules and validation helpers from src/catalog/.
 * @file
 */



/** @typedef {import('./types.js').TypeRule} TypeRule */

/**
 * Find the best matching rule for an entity type list.
 * @param {string[]} types
 * @returns {TypeRule|null}
 */
function matchRule(types) {
  return matchRuleInCatalog(RICH_RESULT_RULES, types);
}


/**
 * Normalize page snapshot into flat entities.
 * @file
 */

/** @typedef {import('./types.js').PageSnapshot} PageSnapshot */
/** @typedef {import('./types.js').Entity} Entity */
/** @typedef {import('./types.js').NormalizedBlock} NormalizedBlock */
/** @typedef {import('./types.js').NormalizeResult} NormalizeResult */

const SCHEMA_PREFIX_RE = /^(?:https?:\/\/schema\.org\/|schema:)/i;

/**
 * Strip schema.org URI prefix from a type string.
 * @param {string} type
 * @returns {string}
 */
function stripSchemaPrefix(type) {
  if (!type || typeof type !== 'string') return type;
  return type.replace(SCHEMA_PREFIX_RE, '');
}

/**
 * @param {unknown} typeField
 * @returns {string[]}
 */
function extractTypes(typeField) {
  if (!typeField) return [];
  const raw = Array.isArray(typeField) ? typeField : [typeField];
  const types = [];
  for (const t of raw) {
    if (typeof t === 'string') {
      const stripped = stripSchemaPrefix(t.trim());
      if (stripped) types.push(stripped);
    }
  }
  return types;
}

/**
 * @param {string} format
 * @param {number} sourceIndex
 * @param {string} basePath
 * @param {unknown} value
 * @param {Entity[]} entities
 * @param {string[]} entityIds
 */
/**
 * @param {string} format
 * @param {number} sourceIndex
 * @param {string} basePath
 * @param {unknown} value
 * @param {Entity[]} entities
 * @param {string[]} entityIds
 * @param {unknown} [inheritedContext]
 */
function flattenJsonValue(format, sourceIndex, basePath, value, entities, entityIds, inheritedContext, depth = 0) {
  if (depth > 50) return;
  if (value === null || value === undefined) return;

  if (Array.isArray(value)) {
    value.forEach((item, i) => {
      flattenJsonValue(format, sourceIndex, `${basePath}[${i}]`, item, entities, entityIds, inheritedContext, depth + 1);
    });
    return;
  }

  if (typeof value !== 'object') return;

  const obj = /** @type {Record<string, unknown>} */ (value);
  const context = obj['@context'] !== undefined ? obj['@context'] : inheritedContext;
  const graph = obj['@graph'];

  if (graph !== undefined) {
    flattenJsonValue(format, sourceIndex, `${basePath}/@graph`, graph, entities, entityIds, context, depth + 1);
    const restKeys = Object.keys(obj).filter((k) => k !== '@graph');
    const hasEntityData = restKeys.some((k) => k !== '@context' && k !== '@id');
    if (hasEntityData) {
      const rest = { ...obj };
      delete rest['@graph'];
      if (rest['@context'] === undefined && context !== undefined) rest['@context'] = context;
      addEntity(format, sourceIndex, basePath, rest, entities, entityIds);
    }
    return;
  }

  const data = context !== undefined && obj['@context'] === undefined
    ? { '@context': context, ...obj }
    : obj;
  addEntity(format, sourceIndex, basePath, data, entities, entityIds);
}

/**
 * @param {string} format
 * @param {number} sourceIndex
 * @param {string} path
 * @param {Record<string, unknown>} data
 * @param {Entity[]} entities
 * @param {string[]} entityIds
 */
function addEntity(format, sourceIndex, path, data, entities, entityIds) {
  if (entities.length >= 1000) return;
  const types = extractTypes(data['@type']);
  const idField = data['@id'];
  const preferredId = typeof idField === 'string' && idField
    ? idField
    : `${format}:${sourceIndex}:${path}`;
  const id = uniqueEntityId(preferredId, entities);

  const entity = {
    id,
    types,
    format,
    sourceIndex,
    data,
    path,
  };
  entities.push(entity);
  entityIds.push(id);
}

/**
 * @param {string} preferredId
 * @param {Entity[]} entities
 */
function uniqueEntityId(preferredId, entities) {
  if (!entities.some((entity) => entity.id === preferredId)) return preferredId;
  let duplicate = 2;
  while (entities.some((entity) => entity.id === `${preferredId}#duplicate-${duplicate}`)) {
    duplicate++;
  }
  return `${preferredId}#duplicate-${duplicate}`;
}

/**
 * @param {import('./types.js').MarkupNode} node
 * @param {number} sourceIndex
 * @param {Entity[]} entities
 * @param {string[]} entityIds
 */
function normalizeMarkupValue(value, depth = 0) {
  if (depth > 50 || value === null || value === undefined) return value;
  if (Array.isArray(value)) return value.map((item) => normalizeMarkupValue(item, depth + 1));
  if (typeof value !== 'object') return value;

  const obj = /** @type {Record<string, unknown>} */ (value);
  if (
    (obj.format === 'microdata' || obj.format === 'rdfa') &&
    'type' in obj &&
    obj.properties &&
    typeof obj.properties === 'object'
  ) {
    const typeField = obj.type;
    const types = Array.isArray(typeField)
      ? typeField.map((type) => stripSchemaPrefix(String(type))).filter(Boolean)
      : typeof typeField === 'string'
        ? typeField.split(/\s+/).map((type) => stripSchemaPrefix(type)).filter(Boolean)
        : [];
    const data = {};
    for (const [property, child] of Object.entries(/** @type {Record<string, unknown>} */ (obj.properties))) {
      data[stripSchemaPrefix(property)] = normalizeMarkupValue(child, depth + 1);
    }
    if (types.length) data['@type'] = types.length === 1 ? types[0] : types;
    return data;
  }

  const normalized = {};
  for (const [key, child] of Object.entries(obj)) {
    normalized[key] = normalizeMarkupValue(child, depth + 1);
  }
  return normalized;
}

function normalizeMarkupNode(node, sourceIndex, entities, entityIds) {
  const normalizedNode = /** @type {Record<string, unknown>} */ (normalizeMarkupValue(node));
  const typeField = normalizedNode['@type'];
  let types;
  if (Array.isArray(typeField)) {
    types = typeField.map((t) => stripSchemaPrefix(String(t)));
  } else if (typeof typeField === 'string') {
    types = typeField.split(/\s+/).map((t) => stripSchemaPrefix(t)).filter(Boolean);
  } else {
    types = [];
  }

  const data = normalizedNode;

  const idField = data['@id'];
  const preferredId = typeof idField === 'string' && idField
    ? idField
    : `${node.format}:${sourceIndex}`;
  const id = uniqueEntityId(preferredId, entities);
  const entity = {
    id,
    types,
    format: node.format,
    sourceIndex,
    data,
    path: node.selector,
  };
  entities.push(entity);
  entityIds.push(id);
}

/**
 * Flatten snapshot markup into entities and source blocks.
 * @param {PageSnapshot} snapshot
 * @returns {NormalizeResult}
 */
function normalize(snapshot) {
  /** @type {NormalizedBlock[]} */
  const blocks = [];
  /** @type {Entity[]} */
  const entities = [];

  for (const block of snapshot.jsonld) {
    const entityIds = [];
    if (block.parsed !== null && typeof block.parsed === 'object') {
      flattenJsonValue('jsonld', block.index, '$', block.parsed, entities, entityIds);
    }
    blocks.push({
      format: 'jsonld',
      sourceIndex: block.index,
      selector: block.selector,
      entityIds,
    });
  }

  snapshot.microdata.forEach((node, i) => {
    const entityIds = [];
    normalizeMarkupNode(node, i, entities, entityIds);
    blocks.push({
      format: 'microdata',
      sourceIndex: i,
      selector: node.selector,
      entityIds,
    });
  });

  snapshot.rdfa.forEach((node, i) => {
    const entityIds = [];
    normalizeMarkupNode(node, i, entities, entityIds);
    blocks.push({
      format: 'rdfa',
      sourceIndex: i,
      selector: node.selector,
      entityIds,
    });
  });

  return { blocks, entities };
}


/**
 * Validate snapshot and entities against rules catalog.
 * @file
 */

/** @typedef {import('./types.js').PageSnapshot} PageSnapshot */
/** @typedef {import('./types.js').Entity} Entity */
/** @typedef {import('./types.js').Finding} Finding */

/**
 * @param {Finding[]} findings
 * @param {Finding} finding
 */
function pushFinding(findings, finding) {
  findings.push(finding);
}

/**
 * @param {unknown} val
 * @returns {string|null}
 */
function readName(val) {
  if (typeof val === 'string') return val;
  if (typeof val === 'object' && val !== null) {
    const obj = /** @type {Record<string, unknown>} */ (val);
    if (typeof obj.name === 'string') return obj.name;
  }
  return null;
}

function isLocalBusiness(types) {
  return types.some((type) => LOCAL_BUSINESS_TYPES.has(type));
}

/**
 * Check if author name appears packed with commas (multiple authors in one string).
 * @param {Record<string, unknown>} data
 * @returns {boolean}
 */
function hasPackedAuthorName(data) {
  const author = data.author;
  if (typeof author === 'string') {
    return author.includes(',') && author.split(',').filter((s) => s.trim()).length > 1;
  }
  if (Array.isArray(author)) {
    return author.some((a) => typeof a === 'string' && a.includes(','));
  }
  if (typeof author === 'object' && author !== null) {
    const name = readName(author);
    if (name && name.includes(',') && name.split(',').filter((s) => s.trim()).length > 1) return true;
  }
  return false;
}

/**
 * Validate FAQPage mainEntity structure.
 * @param {Record<string, unknown>} data
 * @returns {Finding[]}
 */
function validateFaqStructure(data) {
  /** @type {Finding[]} */
  const findings = [];
  const main = data.mainEntity;
  const items = Array.isArray(main) ? main : main ? [main] : [];

  if (items.length === 0) {
    findings.push({
      severity: 'error',
      code: 'FAQ_EMPTY_MAIN_ENTITY',
      message: 'FAQPage mainEntity must contain Question items.',
      path: 'mainEntity',
      docsUrl: FAQ_GOOGLE_STATUS.docsUrl,
    });
    return findings;
  }

  items.forEach((item, i) => {
    if (typeof item !== 'object' || item === null) {
      findings.push({
        severity: 'error',
        code: 'FAQ_INVALID_QUESTION',
        message: `FAQ item ${i + 1} must be a Question object.`,
        path: `mainEntity[${i}]`,
      });
      return;
    }
    const q = /** @type {Record<string, unknown>} */ (item);
    const qTypes = q['@type'];
    const typeList = Array.isArray(qTypes) ? qTypes : qTypes ? [qTypes] : [];
    const isQuestion = typeList.some((t) => String(t).includes('Question'));
    if (!hasProperty(q, 'name')) {
      findings.push({
        severity: 'error',
        code: 'FAQ_MISSING_QUESTION_NAME',
        message: `FAQ Question ${i + 1} is missing name.`,
        path: `mainEntity[${i}].name`,
      });
    }
    if (!isQuestion) {
      findings.push({
        severity: 'warning',
        code: 'FAQ_INVALID_QUESTION_TYPE',
        message: `FAQ item ${i + 1} should have @type Question.`,
        path: `mainEntity[${i}].@type`,
      });
    }
    const answer = q.acceptedAnswer;
    if (!answer) {
      findings.push({
        severity: 'error',
        code: 'FAQ_MISSING_ANSWER',
        message: `FAQ Question ${i + 1} is missing acceptedAnswer.`,
        path: `mainEntity[${i}].acceptedAnswer`,
      });
    } else if (typeof answer === 'object' && answer !== null) {
      const a = /** @type {Record<string, unknown>} */ (answer);
      if (!hasProperty(a, 'text') && !hasProperty(a, 'name')) {
        findings.push({
          severity: 'warning',
          code: 'FAQ_ANSWER_MISSING_TEXT',
          message: `FAQ acceptedAnswer ${i + 1} should include text.`,
          path: `mainEntity[${i}].acceptedAnswer.text`,
        });
      }
    }
  });

  return findings;
}

/**
 * Validate BreadcrumbList itemListElement.
 * @param {Record<string, unknown>} data
 * @returns {Finding[]}
 */
function validateBreadcrumbStructure(data) {
  /** @type {Finding[]} */
  const findings = [];
  const list = data.itemListElement;
  const items = Array.isArray(list) ? list : list ? [list] : [];

  if (items.length < 2) {
    findings.push({
      severity: 'warning',
      code: 'BREADCRUMB_TOO_SHORT',
      message: 'BreadcrumbList should have at least 2 ListItem elements.',
      path: 'itemListElement',
    });
  }

  items.forEach((item, i) => {
    if (typeof item !== 'object' || item === null) return;
    const li = /** @type {Record<string, unknown>} */ (item);
    if (!hasProperty(li, 'name')) {
      findings.push({
        severity: 'error',
        code: 'BREADCRUMB_MISSING_NAME',
        message: `Breadcrumb ListItem ${i + 1} is missing name.`,
        path: `itemListElement[${i}].name`,
      });
    }
    if (li.position === undefined) {
      findings.push({
        severity: 'warning',
        code: 'BREADCRUMB_MISSING_POSITION',
        message: `Breadcrumb ListItem ${i + 1} is missing position.`,
        path: `itemListElement[${i}].position`,
      });
    }
    if (i < items.length - 1 && !hasProperty(li, 'item')) {
      findings.push({
        severity: 'warning',
        code: 'BREADCRUMB_MISSING_ITEM',
        message: `Breadcrumb ListItem ${i + 1} is missing item URL.`,
        path: `itemListElement[${i}].item`,
      });
    }
  });

  return findings;
}

/**
 * Validate WebSite SearchAction.
 * @param {Record<string, unknown>} data
 * @returns {Finding[]}
 */
function validateWebSiteSearchAction(data) {
  /** @type {Finding[]} */
  const findings = [];
  const action = data.potentialAction;
  if (!action) return findings;

  const actions = Array.isArray(action) ? action : [action];
  for (const a of actions) {
    if (typeof a !== 'object' || a === null) continue;
    const act = /** @type {Record<string, unknown>} */ (a);
    const types = act['@type'];
    const typeList = Array.isArray(types) ? types : types ? [types] : [];
    if (typeList.some((t) => String(t).includes('SearchAction'))) {
      findings.push({
        severity: 'info',
        code: 'SEARCH_ACTION_GOOGLE_UNSUPPORTED',
        message: 'Google retired the sitelinks search box; SearchAction is no longer needed for that feature.',
        path: 'potentialAction',
        docsUrl: 'https://developers.google.com/search/blog/2024/10/sitelinks-search-box',
      });
      break;
    }
  }
  return findings;
}

/**
 * Validate JobPosting hiringOrganization.
 * @param {Record<string, unknown>} data
 * @returns {Finding[]}
 */
function validateJobPosting(data) {
  /** @type {Finding[]} */
  const findings = [];
  const org = data.hiringOrganization;
  if (typeof org === 'object' && org !== null) {
    const o = /** @type {Record<string, unknown>} */ (org);
    if (!hasProperty(o, 'name') && !hasProperty(o, 'sameAs')) {
      findings.push({
        severity: 'warning',
        code: 'JOB_MISSING_ORG_NAME',
        message: 'JobPosting hiringOrganization should include name or sameAs.',
        path: 'hiringOrganization.name',
      });
    }
  }
  return findings;
}

/**
 * Validate QAPage mainEntity.
 * @param {Record<string, unknown>} data
 * @returns {Finding[]}
 */
function validateQAPage(data) {
  /** @type {Finding[]} */
  const findings = [];
  const main = data.mainEntity;
  if (!main) return findings;
  const items = Array.isArray(main) ? main : [main];
  items.forEach((item, i) => {
    if (typeof item !== 'object' || item === null) return;
    const q = /** @type {Record<string, unknown>} */ (item);
    if (!hasProperty(q, 'name')) {
      findings.push({
        severity: 'error',
        code: 'QA_MISSING_QUESTION_NAME',
        message: `QAPage Question ${i + 1} is missing name.`,
        path: `mainEntity[${i}].name`,
      });
    }
    if (!q.acceptedAnswer && !q.suggestedAnswer) {
      findings.push({
        severity: 'error',
        code: 'QA_MISSING_ANSWER',
        message: `QAPage Question ${i + 1} needs acceptedAnswer or suggestedAnswer.`,
        path: `mainEntity[${i}]`,
      });
    }
  });
  return findings;
}

/**
 * @param {Record<string, unknown>} data
 * @returns {Finding[]}
 */
function validateDiscussionPost(data) {
  /** @type {Finding[]} */
  const findings = [];
  const hasContent =
    hasProperty(data, 'text') ||
    hasProperty(data, 'image') ||
    hasProperty(data, 'video') ||
    hasProperty(data, 'url');
  if (!hasContent) {
    findings.push({
      severity: 'error',
      code: 'FORUM_MISSING_CONTENT',
      message: 'DiscussionForumPosting requires text, image, video, or a URL to the full post.',
      path: 'text',
      docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/discussion-forum',
    });
  }
  return findings;
}

/**
 * @param {Record<string, unknown>} data
 * @returns {Finding[]}
 */
function validateProfilePage(data) {
  const main = data.mainEntity;
  if (main === undefined || main === null) return [];
  if (typeof main !== 'object' || Array.isArray(main)) {
    return [{
      severity: 'error',
      code: 'PROFILE_INVALID_MAIN_ENTITY',
      message: 'ProfilePage mainEntity must be a Person or Organization object.',
      path: 'mainEntity',
      docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/profile-page',
    }];
  }
  const entity = /** @type {Record<string, unknown>} */ (main);
  const types = entity['@type'];
  const typeList = Array.isArray(types) ? types : types ? [types] : [];
  const isProfileSubject = typeList.some((type) => {
    const value = String(type);
    return value === 'Person' || value === 'Organization' || /(?:schema\.org\/|schema:)(Person|Organization)$/.test(value);
  });
  if (!isProfileSubject) {
    return [{
      severity: 'error',
      code: 'PROFILE_INVALID_MAIN_ENTITY',
      message: 'ProfilePage mainEntity must be a Person or Organization object.',
      path: 'mainEntity.@type',
      docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/profile-page',
    }];
  }
  if (hasProperty(entity, 'name') || hasProperty(entity, 'alternateName')) return [];
  return [{
    severity: 'error',
    code: 'PROFILE_MISSING_IDENTITY',
    message: 'ProfilePage mainEntity requires name or alternateName.',
    path: 'mainEntity.name',
    docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/profile-page',
  }];
}

/**
 * @param {Record<string, unknown>} data
 * @returns {Finding[]}
 */
function validateSoftwareApplication(data) {
  /** @type {Finding[]} */
  const findings = [];
  const offers = Array.isArray(data.offers) ? data.offers : [data.offers];
  const hasOfferPrice = offers.some((offer) => {
    return typeof offer === 'object' && offer !== null && hasProperty(/** @type {Record<string, unknown>} */ (offer), 'price');
  });
  if (!hasOfferPrice) {
    findings.push({
      severity: 'error',
      code: 'SOFTWARE_MISSING_OFFER_PRICE',
      message: 'SoftwareApplication requires offers.price for Google rich-result eligibility.',
      path: 'offers.price',
      docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/software-app',
    });
  }
  if (!hasProperty(data, 'aggregateRating') && !hasProperty(data, 'review')) {
    findings.push({
      severity: 'error',
      code: 'SOFTWARE_MISSING_RATING_OR_REVIEW',
      message: 'SoftwareApplication requires aggregateRating or review for Google rich-result eligibility.',
      path: 'aggregateRating',
      docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/software-app',
    });
  }
  return findings;
}

/**
 * Validate return-policy objects embedded in Organization or Product markup.
 * @param {Record<string, unknown>} data
 * @returns {Finding[]}
 */
function validateNestedMerchantReturnPolicies(data) {
  /** @type {Finding[]} */
  const findings = [];

  function visit(value, path, depth) {
    if (depth > 50 || value === null || value === undefined) return;
    if (Array.isArray(value)) {
      value.forEach((item, index) => visit(item, `${path}[${index}]`, depth + 1));
      return;
    }
    if (typeof value !== 'object') return;
    const obj = /** @type {Record<string, unknown>} */ (value);
    const types = obj['@type'];
    const typeList = Array.isArray(types) ? types : types ? [types] : [];
    if (typeList.some((type) => String(type).endsWith('MerchantReturnPolicy'))) {
      findings.push(...validateMerchantReturnPolicy(obj).map((finding) => ({
        ...finding,
        path: path ? `${path}.${finding.path}` : finding.path,
      })));
    }
    for (const [key, child] of Object.entries(obj)) {
      visit(child, path ? `${path}.${key}` : key, depth + 1);
    }
  }

  for (const [key, value] of Object.entries(data)) visit(value, key, 0);
  return findings;
}

/**
 * @param {Record<string, unknown>} data
 * @returns {Finding[]}
 */
function validateMerchantReturnPolicy(data) {
  if (hasProperty(data, 'merchantReturnLink')) return [];
  /** @type {Finding[]} */
  const findings = [];
  if (!hasProperty(data, 'applicableCountry')) {
    findings.push({
      severity: 'error',
      code: 'RETURN_POLICY_MISSING_COUNTRY',
      message: 'MerchantReturnPolicy requires applicableCountry unless merchantReturnLink is used.',
      path: 'applicableCountry',
      docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/return-policy',
    });
  }
  if (!hasProperty(data, 'returnPolicyCategory')) {
    findings.push({
      severity: 'error',
      code: 'RETURN_POLICY_MISSING_CATEGORY',
      message: 'MerchantReturnPolicy requires returnPolicyCategory unless merchantReturnLink is used.',
      path: 'returnPolicyCategory',
      docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/return-policy',
    });
  } else if (
    String(data.returnPolicyCategory).endsWith('MerchantReturnFiniteReturnWindow') &&
    !hasProperty(data, 'merchantReturnDays')
  ) {
    findings.push({
      severity: 'error',
      code: 'RETURN_POLICY_MISSING_DAYS',
      message: 'A finite MerchantReturnPolicy requires merchantReturnDays.',
      path: 'merchantReturnDays',
      docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/return-policy',
    });
  }
  return findings;
}

/**
 * @param {Record<string, unknown>} rating
 * @param {string} path
 * @returns {Finding[]}
 */
function validateRatingObject(rating, path) {
  /** @type {Finding[]} */
  const findings = [];
  const raw = rating.ratingValue;
  const num = typeof raw === 'number' ? raw : typeof raw === 'string' ? Number(raw) : NaN;
  const best = typeof rating.bestRating === 'number' ? rating.bestRating
    : typeof rating.bestRating === 'string' ? Number(rating.bestRating) : 5;
  const worst = typeof rating.worstRating === 'number' ? rating.worstRating
    : typeof rating.worstRating === 'string' ? Number(rating.worstRating) : 1;
  if (raw === undefined || raw === null || raw === '') {
    findings.push({
      severity: 'error',
      code: 'RATING_MISSING_VALUE',
      message: `Rating at ${path} is missing ratingValue.`,
      path: `${path}.ratingValue`,
    });
    return findings;
  }
  if (Number.isNaN(num)) {
    findings.push({
      severity: 'error',
      code: 'RATING_NOT_NUMERIC',
      message: `Rating value "${String(raw)}" at ${path} is not numeric.`,
      path: `${path}.ratingValue`,
    });
    return findings;
  }
  if (num < worst || num > best) {
    findings.push({
      severity: 'warning',
      code: 'RATING_OUT_OF_BOUNDS',
      message: `Rating ${num} at ${path} is outside ${worst}–${best}.`,
      path: `${path}.ratingValue`,
    });
  }
  return findings;
}

/**
 * @param {Entity} entity
 * @returns {Finding[]}
 */
function validateEntity(entity) {
  /** @type {Finding[]} */
  const findings = [];
  const { types, data, id, format } = entity;

  if (types.length === 0) {
    pushFinding(findings, {
      severity: 'error',
      code: 'MISSING_TYPE',
      message: 'Entity is missing @type.',
      entityId: id,
      path: entity.path,
    });
  }

  for (const dep of DEPRECATED_TYPES) {
    if (types.includes(dep)) {
      pushFinding(findings, {
        severity: 'info',
        code: `${dep.toUpperCase()}_GOOGLE_UNSUPPORTED`,
        message: `${dep} structured data is no longer supported as a Google rich result.`,
        entityId: id,
        path: entity.path,
        docsUrl: 'https://developers.google.com/search/updates',
      });
    }
  }

  if (format === 'jsonld' && !('@context' in data)) {
    pushFinding(findings, {
      severity: 'warning',
      code: 'MISSING_CONTEXT',
      message: 'JSON-LD entity block is missing @context.',
      entityId: id,
      path: '@context',
      docsUrl: 'https://schema.org/docs/gs.html',
    });
  }

  if (format === 'jsonld' && '@context' in data) {
    const ctx = data['@context'];
    const ctxStr = typeof ctx === 'string' ? ctx : JSON.stringify(ctx);
    if (!ctxStr || !ctxStr.includes('schema.org')) {
      pushFinding(findings, {
        severity: 'warning',
        code: 'NON_SCHEMA_CONTEXT',
        message: `@context does not reference schema.org${ctxStr ? `: ${ctxStr.slice(0, 80)}` : '.'}`,
        entityId: id,
        path: '@context',
      });
    }
  }

  for (const rule of RICH_RESULT_RULES.filter((candidate) => {
    return types.includes(candidate.type) || (candidate.type === 'LocalBusiness' && isLocalBusiness(types));
  })) {
    for (const req of rule.required) {
      if (!hasProperty(data, req)) {
        pushFinding(findings, {
          severity: 'error',
          code: `MISSING_${req.toUpperCase()}`,
          message: `${rule.type} is missing required property "${req}".`,
          entityId: id,
          path: req,
          docsUrl: rule.docsUrl,
        });
      }
    }
    for (const rec of rule.recommended) {
      if (!hasProperty(data, rec)) {
        pushFinding(findings, {
          severity: 'info',
          code: `RECOMMENDED_${rec.toUpperCase()}`,
          message: `${rule.type} is missing recommended property "${rec}".`,
          entityId: id,
          path: rec,
          docsUrl: rule.docsUrl,
        });
      }
    }
  }

  if (types.includes('Product')) {
    const hasOfferSignal =
      hasProperty(data, 'offers') ||
      hasProperty(data, 'review') ||
      hasProperty(data, 'aggregateRating');
    if (!hasOfferSignal) {
      pushFinding(findings, {
        severity: 'warning',
        code: 'PRODUCT_MISSING_OFFER_OR_REVIEW',
        message: 'Product should include offers, review, or aggregateRating to qualify for rich results.',
        entityId: id,
        path: 'offers',
        docsUrl: 'https://developers.google.com/search/docs/appearance/structured-data/product',
      });
    }
  }

  if (types.includes('FAQPage')) {
    findings.push(...validateFaqStructure(data).map((f) => ({ ...f, entityId: id })));
    pushFinding(findings, {
      severity: 'info',
      code: FAQ_GOOGLE_STATUS.code,
      message: FAQ_GOOGLE_STATUS.message,
      entityId: id,
      docsUrl: FAQ_GOOGLE_STATUS.docsUrl,
    });
  }

  if (types.includes('BreadcrumbList')) {
    findings.push(...validateBreadcrumbStructure(data).map((f) => ({ ...f, entityId: id })));
  }

  if (types.includes('WebSite')) {
    findings.push(...validateWebSiteSearchAction(data).map((f) => ({ ...f, entityId: id })));
  }

  if (types.includes('SearchAction')) {
    pushFinding(findings, {
      severity: 'info',
      code: 'SEARCH_ACTION_GOOGLE_UNSUPPORTED',
      message: 'Google retired the sitelinks search box; SearchAction is no longer needed for that feature.',
      entityId: id,
      path: entity.path,
      docsUrl: 'https://developers.google.com/search/blog/2024/10/sitelinks-search-box',
    });
  }

  if (types.includes('JobPosting')) {
    findings.push(...validateJobPosting(data).map((f) => ({ ...f, entityId: id })));
  }

  if (types.includes('QAPage')) {
    findings.push(...validateQAPage(data).map((f) => ({ ...f, entityId: id })));
  }

  if (types.includes('DiscussionForumPosting') || types.includes('SocialMediaPosting')) {
    findings.push(...validateDiscussionPost(data).map((f) => ({ ...f, entityId: id })));
  }

  if (types.includes('ProfilePage')) {
    findings.push(...validateProfilePage(data).map((f) => ({ ...f, entityId: id })));
  }

  if (types.includes('MerchantReturnPolicy')) {
    findings.push(...validateMerchantReturnPolicy(data).map((f) => ({ ...f, entityId: id })));
  }

  if (types.includes('SoftwareApplication')) {
    findings.push(...validateSoftwareApplication(data).map((f) => ({ ...f, entityId: id })));
  }

  findings.push(...validateNestedMerchantReturnPolicies(data).map((f) => ({ ...f, entityId: id })));

  if (hasPackedAuthorName(data)) {
    pushFinding(findings, {
      severity: 'warning',
      code: 'PACKED_AUTHOR_NAME',
      message: 'Author name appears to contain multiple names packed with commas; use separate author objects.',
      entityId: id,
      path: 'author',
    });
  }

  for (const { path, value } of collectUrlFields(data)) {
    if (isRelativeUrl(value)) {
      pushFinding(findings, {
        severity: 'warning',
        code: 'RELATIVE_URL',
        message: `Relative URL in "${path}": ${value}`,
        entityId: id,
        path,
      });
    }
  }

  for (const check of collectValueChecks(data)) {
    if (check.kind === 'date') {
      const text = String(check.value);
      if (!isIso8601Date(text)) {
        pushFinding(findings, {
          severity: 'warning',
          code: 'INVALID_DATE',
          message: `"${text}" at ${check.path} is not a valid ISO 8601 date.`,
          entityId: id,
          path: check.path,
        });
      }
    } else if (check.kind === 'currency') {
      const text = String(check.value).trim();
      if (!isIso4217Currency(text)) {
        pushFinding(findings, {
          severity: 'warning',
          code: 'INVALID_CURRENCY',
          message: `"${text}" at ${check.path} is not a 3-letter ISO 4217 currency code.`,
          entityId: id,
          path: check.path,
        });
      }
    } else if (check.kind === 'rating' && check.value && typeof check.value === 'object') {
      findings.push(
        ...validateRatingObject(/** @type {Record<string, unknown>} */ (check.value), check.path)
          .map((f) => ({ ...f, entityId: id })),
      );
    }
  }

  return findings;
}

/**
 * Validate page snapshot and normalized entities.
 * @param {PageSnapshot} snapshot
 * @param {Entity[]} entities
 * @returns {Finding[]}
 */
function validate(snapshot, entities) {
  /** @type {Finding[]} */
  const findings = [];

  for (const block of snapshot.jsonld) {
    if (block.parseError) {
      const loc = block.parseError.line
        ? ` (line ${block.parseError.line}, column ${block.parseError.column ?? '?'})`
        : '';
      pushFinding(findings, {
        severity: 'error',
        code: 'JSONLD_PARSE',
        message: `JSON-LD parse error${loc}: ${block.parseError.message}`,
        path: block.selector,
      });
    }
    if (block.parsed === null && !block.parseError) {
      pushFinding(findings, {
        severity: 'error',
        code: 'JSONLD_EMPTY',
        message: 'JSON-LD block is empty or failed to parse.',
        path: block.selector,
      });
    } else if (block.parsed !== null && !block.parseError) {
      if (Array.isArray(block.parsed) && block.parsed.length === 0) {
        pushFinding(findings, {
          severity: 'error',
          code: 'JSONLD_EMPTY',
          message: 'JSON-LD block contains an empty top-level array.',
          path: block.selector,
        });
      } else if (
        typeof block.parsed !== 'object' ||
        (Array.isArray(block.parsed) && block.parsed.some((item) => {
          return typeof item !== 'object' || item === null || Array.isArray(item);
        }))
      ) {
        pushFinding(findings, {
          severity: 'error',
          code: 'JSONLD_INVALID_TOP_LEVEL',
          message: 'JSON-LD top-level value must be an object or an array of objects.',
          path: block.selector,
        });
      } else if (
        !Array.isArray(block.parsed) &&
        '@graph' in /** @type {Record<string, unknown>} */ (block.parsed) &&
        (
          /** @type {Record<string, unknown>} */ (block.parsed)['@graph'] === null ||
          typeof /** @type {Record<string, unknown>} */ (block.parsed)['@graph'] !== 'object' ||
          (Array.isArray(/** @type {Record<string, unknown>} */ (block.parsed)['@graph']) &&
            /** @type {unknown[]} */ (/** @type {Record<string, unknown>} */ (block.parsed)['@graph']).length === 0)
        )
      ) {
        pushFinding(findings, {
          severity: 'error',
          code: 'JSONLD_EMPTY',
          message: 'JSON-LD @graph must contain an array of entity objects.',
          path: block.selector,
        });
      } else if (
        !Array.isArray(block.parsed) &&
        Array.isArray(/** @type {Record<string, unknown>} */ (block.parsed)['@graph']) &&
        /** @type {unknown[]} */ (/** @type {Record<string, unknown>} */ (block.parsed)['@graph']).some((item) => {
          return typeof item !== 'object' || item === null || Array.isArray(item);
        })
      ) {
        pushFinding(findings, {
          severity: 'error',
          code: 'JSONLD_INVALID_GRAPH',
          message: 'JSON-LD @graph entries must be entity objects.',
          path: block.selector,
        });
      }
    }
  }

  if (
    entities.length === 0 &&
    snapshot.jsonld.length === 0 &&
    snapshot.microdata.length === 0 &&
    snapshot.rdfa.length === 0
  ) {
    pushFinding(findings, {
      severity: 'info',
      code: 'NO_SCHEMA',
      message: 'No structured data (JSON-LD, Microdata, or RDFa) found on this page.',
    });
    return findings;
  }

  for (const entity of entities) {
    findings.push(...validateEntity(entity));
  }

  return findings;
}


/**
 * Score findings and entities on a 0–100 scale.
 * @file
 */

/** @typedef {import('./types.js').Entity} Entity */
/** @typedef {import('./types.js').Finding} Finding */
/** @typedef {import('./types.js').ScoreResult} ScoreResult */
/** @typedef {import('./types.js').ScoreLabel} ScoreLabel */

function matchingRules(entity) {
  return RICH_RESULT_RULES.filter((rule) => {
    return entity.types.includes(rule.type) || (rule.type === 'LocalBusiness' && entity.types.some((type) => LOCAL_BUSINESS_TYPES.has(type)));
  });
}

/**
 * @param {number} total
 * @returns {ScoreLabel}
 */
function labelFromTotal(total) {
  if (total >= 90) return 'excellent';
  if (total >= 70) return 'good';
  if (total >= 50) return 'fair';
  return 'poor';
}

/**
 * @param {Entity[]} entities
 * @returns {number}
 */
function coverageBonus(entities) {
  const qualifying = entities.filter((entity) => matchingRules(entity).length > 0);
  if (qualifying.length === 0) return 0;
  const formats = new Set(qualifying.map((entity) => entity.format));
  return Math.min(qualifying.length * 5 + formats.size * 5, 15);
}

/**
 * @param {Entity[]} entities
 * @returns {number}
 */
function richnessBonus(entities) {
  let bonus = 0;
  for (const entity of entities) {
    const meaningful = new Set(
      matchingRules(entity).flatMap((rule) => [...rule.required, ...rule.recommended]),
    );
    for (const property of meaningful) {
      if (property in entity.data) bonus += 1;
    }
  }
  return Math.min(bonus, 15);
}

/**
 * Compute schema quality score.
 * @param {Finding[]} findings
 * @param {Entity[]} entities
 * @returns {ScoreResult}
 */
function score(findings, entities) {
  const errorCount = findings.filter((f) => f.severity === 'error').length;
  const warningCount = findings.filter((f) => f.severity === 'warning').length;

  if (entities.length === 0) {
    return {
      total: 0,
      label: 'none',
      breakdown: { coverage: 0, validity: 0, richness: 0, agent: 0 },
      errorCount,
      warningCount,
    };
  }

  const qualifying = entities.some((entity) => matchingRules(entity).length > 0);
  const coverage = coverageBonus(entities);
  const richness = richnessBonus(entities);
  const baseValidity = qualifying ? 70 : 40;
  const validity = Math.max(0, baseValidity - errorCount * 12 - warningCount * 4);
  let total = validity + coverage + richness;

  total = Math.round(Math.max(0, Math.min(100, total)));

  return {
    total,
    label: labelFromTotal(total),
    breakdown: {
      coverage: Math.min(coverage, 15),
      validity,
      richness: Math.min(richness, 15),
      agent: 0,
    },
    errorCount,
    warningCount,
  };
}


/**
 * Agent-friendly bundle export.
 * @file
 */

/** @typedef {import('./types.js').PageSnapshot} PageSnapshot */
/** @typedef {import('./types.js').Entity} Entity */
/** @typedef {import('./types.js').Finding} Finding */
/** @typedef {import('./types.js').ScoreResult} ScoreResult */
/** @typedef {import('./types.js').AgentBundle} AgentBundle */

/**
 * @param {object} input
 * @param {PageSnapshot} input.snapshot
 * @param {Entity[]} input.entities
 * @param {Finding[]} input.findings
 * @param {ScoreResult} input.score
 * @returns {AgentBundle}
 */
function buildAgentBundle({ snapshot, entities, findings, score: scoreResult }) {
  const errors = findings.filter((f) => f.severity === 'error').length;
  const warnings = findings.filter((f) => f.severity === 'warning').length;

  return {
    version: 1,
    tool: 'schema-devtools',
    url: snapshot.url,
    title: snapshot.title,
    canonical: snapshot.canonical,
    inspectedAt: snapshot.inspectedAt,
    score: scoreResult,
    summary: {
      jsonld: snapshot.jsonld.length,
      microdata: snapshot.microdata.length,
      rdfa: snapshot.rdfa.length,
      entities: entities.length,
      errors,
      warnings,
    },
    entities,
    findings,
    agent: snapshot.agent,
  };
}

/**
 * @param {Finding[]} findings
 * @param {number} limit
 * @returns {string}
 */
function formatFindings(findings, limit) {
  if (findings.length === 0) return 'None';
  return findings.slice(0, limit).map((f) => {
    const prefix = f.severity === 'error' ? '❌' : f.severity === 'warning' ? '⚠️' : 'ℹ️';
    const loc = f.path ? ` (${f.path})` : '';
    return `${prefix} ${f.code}${loc}: ${f.message}`;
  }).join('\n');
}

/**
 * @param {Entity[]} entities
 * @param {number} limit
 * @returns {string}
 */
function formatEntities(entities, limit) {
  if (entities.length === 0) return 'None';
  return entities.slice(0, limit).map((e) => {
    const types = e.types.length ? e.types.join(', ') : 'Untyped';
    return `- ${types} [${e.format}] @ ${e.path}`;
  }).join('\n');
}

/**
 * Convert agent bundle to markdown for LLM paste.
 * @param {AgentBundle} bundle
 * @returns {string}
 */
function toAgentMarkdown(bundle) {
  const lines = [
    '# Schema DevTools Report',
    '',
    `**URL:** ${bundle.url}`,
    `**Title:** ${bundle.title}`,
    bundle.canonical ? `**Canonical:** ${bundle.canonical}` : null,
    `**Inspected:** ${bundle.inspectedAt}`,
    '',
    `## Score: ${bundle.score.total}/100 (${bundle.score.label})`,
    '',
    `- Errors: ${bundle.summary.errors}`,
    `- Warnings: ${bundle.summary.warnings}`,
    `- JSON-LD blocks: ${bundle.summary.jsonld}`,
    `- Microdata items: ${bundle.summary.microdata}`,
    `- RDFa items: ${bundle.summary.rdfa}`,
    `- Entities: ${bundle.summary.entities}`,
    '',
    '## Entities',
    formatEntities(bundle.entities, 20),
    bundle.entities.length > 20 ? `\n… and ${bundle.entities.length - 20} more` : null,
    '',
    '## Findings (top)',
    formatFindings(
      bundle.findings.filter((f) => f.severity === 'error'),
      10,
    ),
    '',
    '### Warnings',
    formatFindings(
      bundle.findings.filter((f) => f.severity === 'warning'),
      10,
    ),
    '',
    '## Agent Surface',
    `- Model context: ${bundle.agent.hasModelContext ? 'yes' : 'no'}`,
    `- llms.txt link hint: ${bundle.agent.hasLlmsTxtLink ? 'yes' : 'no'}`,
    '',
    '---',
    '_Generated by Schema DevTools_',
  ];

  return lines.filter((l) => l !== null).join('\n');
}


global.SchemaDT = {
  extractPageSchema,
  EXTRACT_SOURCE,
  normalize,
  stripSchemaPrefix,
  validate,
  score,
  buildAgentBundle,
  toAgentMarkdown,
};
})(typeof globalThis !== 'undefined' ? globalThis : window);
