import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import vm from 'node:vm';
import { spawnSync } from 'node:child_process';

import { EXTRACT_SOURCE } from '../src/extract.js';
import { normalize } from '../src/normalize.js';
import { validate } from '../src/validate.js';
import { score } from '../src/score.js';
import { RICH_RESULT_RULES } from '../src/catalog/rich-results.js';
import { DEPRECATED_TYPES, FAQ_GOOGLE_STATUS } from '../src/catalog/deprecations.js';
import { matchRuleInCatalog, hasProperty, isIso8601Date, isIso4217Currency } from '../src/catalog/syntax.js';
import { formatEvalException, listen } from '../devtools/host.js';
import { matchesSearch, store, visibleEntities } from '../ui/store.js';

const root = new URL('../', import.meta.url);

console.log('🧪 Running Full Schema DevTools Verification Suite...\n');

// -----------------------------------------------------------------------------
// 1. Bundle Classic Engine
// -----------------------------------------------------------------------------
process.stdout.write('⏳ 1. Bundling Schema Engine... ');
const files = [
  'src/extract.js',
  'src/catalog/rich-results.js',
  'src/catalog/deprecations.js',
  'src/catalog/syntax.js',
  'src/rules.js',
  'src/normalize.js',
  'src/validate.js',
  'src/score.js',
  'src/agent.js',
];

function stripModuleSyntax(code) {
  return code
    .replace(/^\s*import\s+[\s\S]*?from\s+['"][^'"]+['"];?\s*$/gm, '')
    .replace(/^\s*export\s+\{[^}]*\}\s*;?\s*$/gm, '')
    .replace(/^export\s+async\s+function/gm, 'async function')
    .replace(/^export\s+function/gm, 'function')
    .replace(/^export\s+const /gm, 'const ')
    .replace(/^export\s+let /gm, 'let ')
    .replace(/^export\s+var /gm, 'var ')
    .replace(/^export\s+\{[^}]+\}\s+from\s+['"][^'"]+['"];?\s*$/gm, '');
}

const body = files
  .map((rel) => stripModuleSyntax(readFileSync(new URL(rel, root), 'utf8')))
  .join('\n\n');

const out = `/* generated by scripts/bundle.mjs — do not edit by hand */
(function (global) {
${body}

global.SchemaDT = {
  extractPageSchema,
  EXTRACT_SOURCE,
  normalize,
  stripSchemaPrefix,
  validate,
  score,
  buildAgentBundle,
  toAgentMarkdown,
};
})(typeof globalThis !== 'undefined' ? globalThis : window);
`;

writeFileSync(new URL('devtools/engine.classic.js', root), out, 'utf8');

const bundleSource = readFileSync(new URL('devtools/engine.classic.js', root), 'utf8');
assert(!/^\s*(?:import|export)\s/m.test(bundleSource), 'Bundle must contain no import/export statements.');
const sandbox = {};
vm.runInNewContext(bundleSource, sandbox);
assert.equal(typeof sandbox.SchemaDT?.validate, 'function', 'Bundled SchemaDT.validate must be a function.');
assert.equal(typeof sandbox.SchemaDT?.score, 'function', 'Bundled SchemaDT.score must be a function.');
console.log(`✅ Passed (${bundleSource.length} bytes)`);

// -----------------------------------------------------------------------------
// 2. Engine Extraction & Scoring Tests
// -----------------------------------------------------------------------------
process.stdout.write('⏳ 2. Schema Engine & Scoring Tests... ');

function snapshotFor(parsed, agent = { hasModelContext: false, modelContext: null, hasLlmsTxtLink: false }) {
  return {
    url: 'https://example.test/page',
    title: 'Example',
    canonical: 'https://example.test/page',
    robots: null,
    inspectedAt: '2026-08-26T00:00:00.000Z',
    jsonld: [{
      index: 0,
      raw: JSON.stringify(parsed),
      parsed,
      parseError: null,
      selector: 'script:nth-of-type(1)',
      domIndex: 0,
    }],
    microdata: [],
    rdfa: [],
    agent,
  };
}

function runInspect(parsed) {
  const snapshot = snapshotFor(parsed);
  const { entities } = normalize(snapshot);
  const findings = validate(snapshot, entities);
  return { entities, findings, score: score(findings, entities) };
}

function hasCode(result, code) {
  return result.findings.some((finding) => finding.code === code);
}

// Deprecated FAQ
const faq = runInspect({
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [{
    '@type': 'Question',
    name: 'Question?',
    acceptedAnswer: { '@type': 'Answer', text: 'Answer.' },
  }],
});
assert(hasCode(faq, 'FAQ_GOOGLE_UNSUPPORTED'));
assert.equal(faq.findings.filter((f) => f.severity !== 'info').length, 0);
assert.equal(faq.score.total, score([], faq.entities).total);

// Deprecated Sitelinks Searchbox
const website = runInspect({
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  potentialAction: { '@type': 'SearchAction' },
});
assert(hasCode(website, 'SEARCH_ACTION_GOOGLE_UNSUPPORTED'));
assert(!hasCode(website, 'WEBSITE_MISSING_SEARCH_ACTION'));

// Deprecated HowTo
const howTo = runInspect({ '@context': 'https://schema.org', '@type': 'HowTo', name: 'Task' });
assert(hasCode(howTo, 'HOWTO_GOOGLE_UNSUPPORTED'));
assert.equal(howTo.findings.find((f) => f.code === 'HOWTO_GOOGLE_UNSUPPORTED')?.severity, 'info');

// Profile Page
const profile = runInspect({
  '@context': 'https://schema.org',
  '@type': 'ProfilePage',
  mainEntity: { '@type': 'Person' },
});
assert(hasCode(profile, 'PROFILE_MISSING_IDENTITY'));

// Discussion Forum
const forum = runInspect({
  '@context': 'https://schema.org',
  '@type': 'DiscussionForumPosting',
  author: { '@type': 'Person', name: 'A. Person' },
  datePublished: '2026-08-26T12:00:00Z',
  image: 'https://example.test/image.jpg',
});
assert(!hasCode(forum, 'FORUM_MISSING_CONTENT'));

// Return Policy
const finiteReturnPolicy = runInspect({
  '@context': 'https://schema.org',
  '@type': 'MerchantReturnPolicy',
  applicableCountry: 'US',
  returnPolicyCategory: 'https://schema.org/MerchantReturnFiniteReturnWindow',
});
assert(hasCode(finiteReturnPolicy, 'RETURN_POLICY_MISSING_DAYS'));

// Invalid Date
const invalidDate = runInspect({
  '@context': 'https://schema.org',
  '@type': 'Article',
  headline: 'Invalid calendar date',
  datePublished: '2026-02-30',
});
assert(hasCode(invalidDate, 'INVALID_DATE'));

// Agent Score Invariance
const agentEntities = faq.entities;
const plainScore = score([], agentEntities);
const scoreWithIgnoredAgentArgument = score([], agentEntities, {
  hasModelContext: true,
  modelContext: null,
  hasLlmsTxtLink: true,
});
assert.deepEqual(scoreWithIgnoredAgentArgument, plainScore);
assert.equal(plainScore.breakdown.agent, 0);

// Extract Source String
assert.equal(typeof EXTRACT_SOURCE, 'string');
assert(EXTRACT_SOURCE.includes('JSON.stringify(data)'));
assert(EXTRACT_SOURCE.includes("rel.includes('describedby')"));
assert(!EXTRACT_SOURCE.includes('navigator.modelContext'));

// Manifest Checks
const manifest = JSON.parse(readFileSync(new URL('manifest.json', root), 'utf8'));
assert.equal(manifest.manifest_version, 3);
assert(!('host_permissions' in manifest));
assert(!('permissions' in manifest) || manifest.permissions.length === 0);

// Panel Host Source Checks
const panelSource = readFileSync(new URL('devtools/panel.js', root), 'utf8');
assert(panelSource.includes('setThemeChangeHandler'));
assert(!panelSource.includes('panels.onThemeChanged'));
assert(!panelSource.includes('window.__SCHEMA_DEVTOOLS__ ='));
assert(panelSource.includes('PAGE_WATCH_REMOVE'));

console.log('✅ Passed');

// -----------------------------------------------------------------------------
// 3. Declarative Rule Catalog & Syntax Audit
// -----------------------------------------------------------------------------
process.stdout.write('⏳ 3. Rule Catalog & Syntax Audit... ');

assert(Array.isArray(RICH_RESULT_RULES) && RICH_RESULT_RULES.length >= 20, 'Catalog must contain 20+ rich result rules.');
for (const rule of RICH_RESULT_RULES) {
  assert(rule.type, `Rule missing type: ${JSON.stringify(rule)}`);
  assert(rule.docsUrl && /^https?:\/\//i.test(rule.docsUrl), `Rule ${rule.type} has invalid docsUrl: ${rule.docsUrl}`);
  assert(Array.isArray(rule.required), `Rule ${rule.type} required must be an array`);
  assert(Array.isArray(rule.recommended), `Rule ${rule.type} recommended must be an array`);
}

assert(Array.isArray(DEPRECATED_TYPES) && DEPRECATED_TYPES.length >= 2, 'Must contain deprecated types list.');
assert(FAQ_GOOGLE_STATUS.code && FAQ_GOOGLE_STATUS.docsUrl, 'FAQ status must have code and docsUrl');

assert.equal(typeof matchRuleInCatalog, 'function');
assert.equal(typeof hasProperty, 'function');
assert.equal(typeof isIso8601Date, 'function');
assert.equal(typeof isIso4217Currency, 'function');
assert.equal(isIso8601Date('2026-08-26'), true);
assert.equal(isIso8601Date('2026-02-30'), false);
assert.equal(isIso4217Currency('USD'), true);
assert.equal(isIso4217Currency('INVALID'), false);

console.log(`✅ Passed (${RICH_RESULT_RULES.length} active rich-result rules, ${DEPRECATED_TYPES.length} deprecations)`);

// -----------------------------------------------------------------------------
// 4. VanJS Modular UI & DevTools Host Smoke Tests
// -----------------------------------------------------------------------------
process.stdout.write('⏳ 4. VanJS Panel & Sidebar UI Checks... ');

const panelJs = readFileSync(new URL('devtools/panel.js', root), 'utf8');
const panelApp = readFileSync(new URL('ui/app.js', root), 'utf8');
const toolbarJs = readFileSync(new URL('ui/components/toolbar.js', root), 'utf8');
const entityListJs = readFileSync(new URL('ui/components/entity-list.js', root), 'utf8');
const panelHtml = readFileSync(new URL('devtools/panel.html', root), 'utf8');
const themeCss = readFileSync(new URL('ui/theme.css', root), 'utf8');
const vanJs = readFileSync(new URL('vendor/van.js', root), 'utf8');
const vanXJs = readFileSync(new URL('vendor/van-x.js', root), 'utf8');

const sidebarHostJs = readFileSync(new URL('devtools/sidebar.js', root), 'utf8');
const sidebarHtml = readFileSync(new URL('devtools/sidebar.html', root), 'utf8');
const sidebarViewJs = readFileSync(new URL('ui/sidebar-view.js', root), 'utf8');

assert.match(panelHtml, /type="module" src="panel.js"/, 'Panel must load as an ES module.');
assert.match(panelHtml, /href="\.\.\/ui\/panel\.css"/, 'Panel HTML must link ../ui/panel.css.');
assert.match(sidebarHtml, /href="\.\.\/ui\/sidebar\.css"/, 'Sidebar HTML must link ../ui/sidebar.css.');
assert.match(sidebarHostJs, /from '\.\.\/ui\/sidebar-view\.js'/, 'Sidebar host must import ../ui/sidebar-view.js.');
assert.match(panelApp, /from '\.\.\/vendor\/van\.js'/, 'Panel UI must use the vendored VanJS runtime.');
assert.match(panelApp, /van\.tags/, 'Panel UI must use VanJS tag functions.');
assert.match(sidebarViewJs, /van\.tags/, 'Sidebar view must use VanJS tag functions.');
assert.doesNotMatch(panelApp, /\.innerHTML/, 'Panel components must not assign innerHTML.');
assert.doesNotMatch(sidebarViewJs, /\.innerHTML/, 'Sidebar view must not assign innerHTML.');
assert.match(vanJs, /tags:/, 'Vendored VanJS must be self-contained in the extension.');
assert.match(vanXJs, /reactive/, 'Vendored VanX must be self-contained in the extension.');
assert.match(themeCss, /--sys-color-base/, 'Shared theme tokens must include DevTools system colors.');
assert.match(
  panelJs,
  /function selectEntity\(entity, \{ inspect = false, highlight = true \} = \{\}\)/,
  'Entity selection must stay on the Schema tab; inspect() switches DevTools panels.',
);
assert.match(toolbarJs, /id:\s*['"]btn-inspect['"]/, 'Inspect in Elements must remain an explicit action in toolbar.');
assert.match(toolbarJs, /actions\.inspectSelected\(\)/, 'Inspect in Elements must be wired to the explicit button.');
assert.match(
  entityListJs,
  /actions\.selectEntity\(entity,\s*\{\s*inspect:\s*event\.altKey\s*\}\)/,
  'Ordinary entity clicks may inspect only when Alt is held.',
);
assert.doesNotMatch(panelApp, /\.innerHTML/, 'Panel templates must not assign innerHTML.');
assert.doesNotMatch(toolbarJs, /\.innerHTML/, 'Toolbar must not assign innerHTML.');
assert.doesNotMatch(entityListJs, /\.innerHTML/, 'Entity list must not assign innerHTML.');
assert.doesNotMatch(panelJs, /\.innerHTML/, 'Panel analysis must not assign innerHTML.');
assert.match(panelJs, /listen\(chrome\.devtools\?\.network\?\.onNavigated/, 'Navigation refresh must not assume network.onNavigated exists.');
assert.match(panelJs, /formatEvalException/, 'Eval failures must format Chrome exceptionInfo.');

const hostJs = readFileSync(new URL('devtools/host.js', root), 'utf8');
assert.match(hostJs, /details/, 'Eval errors must substitute exceptionInfo.details into description templates.');
assert.match(hostJs, /function listen/, 'Optional Chrome events must be feature-detected before addListener.');

const inspectCalls = [...panelJs.matchAll(/\binspect\(/g)];
assert.equal(inspectCalls.length, 3, 'inspect() must stay limited to inspectExprForEntity.');

const allUi = `${panelJs}\n${panelApp}\n${toolbarJs}\n${entityListJs}`;
const clickSelects = [...allUi.matchAll(/selectEntity\([^)]*\)/g)].map((match) => match[0]);
assert.ok(
  clickSelects.every((call) => !call.includes('inspect: true')),
  'No in-panel click path may hardcode inspect: true.',
);

store.entities = [
  { id: 'entity:1', types: ['Article'], format: 'jsonld', sourceIndex: 0, data: { headline: 'Hello' } },
  { id: 'entity:2', types: ['ImageObject'], format: 'jsonld', sourceIndex: 0, data: { url: 'https://example.com/a.jpg' } },
];
store.query = 'imageobject';
assert.equal(visibleEntities().map((entity) => entity.id).join(','), 'entity:2');
assert.equal(matchesSearch('Article jsonld', 'article'), true);
assert.equal(matchesSearch('Article jsonld', 'product'), false);
store.query = '';

assert.equal(
  formatEvalException({ description: 'Operation failed: %s', details: ['Inspected tab was closed'] }),
  'Operation failed: Inspected tab was closed',
);
assert.equal(formatEvalException({ description: 'Operation failed: %s' }), 'Evaluation failed');
assert.equal(formatEvalException({ isException: true, value: 'page threw' }), 'page threw');
assert.equal(listen(undefined, () => {}), false);
let listened = 0;
assert.equal(listen({ addListener: (handler) => handler() }, () => { listened += 1; }), true);
assert.equal(listened, 1);

console.log('✅ Passed');

// -----------------------------------------------------------------------------
// 5. Security & Dependency Guardrails
// -----------------------------------------------------------------------------
process.stdout.write('⏳ 5. Security & Dependency Guardrails... ');

const agentsCheck = spawnSync('git', ['grep', '\\.agents', '--', ':!.agents', ':!*.md', ':!.cursor', ':!.gitignore', ':!scripts/test.mjs'], { encoding: 'utf8' });
assert.equal(agentsCheck.stdout.trim(), '', 'No production files may reference .agents/');

const usersCheck = spawnSync('git', ['grep', '-i', '/Users/', '--', ':!*.lock', ':!node_modules', ':!scripts/test.mjs'], { encoding: 'utf8' });
assert.equal(usersCheck.stdout.trim(), '', 'No private local paths (/Users/) allowed.');

console.log('✅ Passed');

console.log('\n🎉 All test suites and security guardrails passed cleanly!\n');
