import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import vm from 'node:vm';
import { spawnSync } from 'node:child_process';

import { EXTRACT_SOURCE } from '../src/extract.js';
import { SELECTION_EXTRACT_SOURCE } from '../src/extract-selection.js';
import { normalize } from '../src/normalize.js';
import { validate } from '../src/validate.js';
import { score } from '../src/score.js';
import { RICH_RESULT_RULES } from '../src/catalog/rich-results.js';
import { DEPRECATED_TYPES, FAQ_GOOGLE_STATUS } from '../src/catalog/deprecations.js';
import { matchRuleInCatalog, hasProperty, hasPropertyPath, isIso8601Date, isIso4217Currency } from '../src/catalog/syntax.js';
import { formatEvalException, listen } from '../devtools/host.js';
import { PAGE_WATCH_INSTALL } from '../devtools/page-sources.js';
import { serpCards } from '../ui/features/serp.js';
import { matchesSearch, store, visibleEntities } from '../ui/store.js';
import { FIXTURES } from '../sandbox/fixtures.js';

const root = new URL('../', import.meta.url);

console.log('🧪 Running Full Schema DevTools Verification Suite...\n');

// -----------------------------------------------------------------------------
// 1. Bundle Classic Engine
// -----------------------------------------------------------------------------
process.stdout.write('⏳ 1. Bundling Schema Engine... ');
const files = [
  'src/extract.js',
  'src/extract-selection.js',
  'src/catalog/rich-results.js',
  'src/catalog/deprecations.js',
  'src/catalog/syntax.js',
  'src/rules.js',
  'src/normalize.js',
  'src/validate.js',
  'src/score.js',
  'src/agent.js',
];

function stripModuleSyntax(code) {
  return code
    .replace(/^\s*import\s+[\s\S]*?from\s+['"][^'"]+['"];?\s*$/gm, '')
    .replace(/^\s*export\s+\{[^}]*\}\s*;?\s*$/gm, '')
    .replace(/^export\s+async\s+function/gm, 'async function')
    .replace(/^export\s+function/gm, 'function')
    .replace(/^export\s+const /gm, 'const ')
    .replace(/^export\s+let /gm, 'let ')
    .replace(/^export\s+var /gm, 'var ')
    .replace(/^export\s+\{[^}]+\}\s+from\s+['"][^'"]+['"];?\s*$/gm, '');
}

const body = files
  .map((rel) => stripModuleSyntax(readFileSync(new URL(rel, root), 'utf8')))
  .join('\n\n');

const out = `/* generated by scripts/bundle.mjs — do not edit by hand */
(function (global) {
${body}

global.SchemaDT = {
  extractPageSchema,
  EXTRACT_SOURCE,
  inspectSelectedSchemaNode,
  SELECTION_EXTRACT_SOURCE,
  normalize,
  stripSchemaPrefix,
  validate,
  score,
  buildAgentBundle,
  toAgentMarkdown,
};
})(typeof globalThis !== 'undefined' ? globalThis : window);
`;

writeFileSync(new URL('devtools/engine.classic.js', root), out, 'utf8');

const bundleSource = readFileSync(new URL('devtools/engine.classic.js', root), 'utf8');
assert(!/^\s*(?:import|export)\s/m.test(bundleSource), 'Bundle must contain no import/export statements.');
const sandbox = {};
vm.runInNewContext(bundleSource, sandbox);
assert.equal(typeof sandbox.SchemaDT?.validate, 'function', 'Bundled SchemaDT.validate must be a function.');
assert.equal(typeof sandbox.SchemaDT?.score, 'function', 'Bundled SchemaDT.score must be a function.');
assert.equal(typeof sandbox.SchemaDT?.SELECTION_EXTRACT_SOURCE, 'string', 'Bundle must expose selected-node extraction source.');
assert.equal(typeof SELECTION_EXTRACT_SOURCE, 'string', 'Selected-node extraction source must be serializable.');
console.log(`✅ Passed (${bundleSource.length} bytes)`);

// -----------------------------------------------------------------------------
// 2. Engine Extraction & Scoring Tests
// -----------------------------------------------------------------------------
process.stdout.write('⏳ 2. Schema Engine & Scoring Tests... ');

function snapshotFor(parsed, agent = { hasModelContext: false, modelContext: null, hasLlmsTxtLink: false }) {
  return {
    url: 'https://example.test/page',
    title: 'Example',
    canonical: 'https://example.test/page',
    robots: null,
    inspectedAt: '2026-08-26T00:00:00.000Z',
    jsonld: [{
      index: 0,
      raw: JSON.stringify(parsed),
      parsed,
      parseError: null,
      selector: 'script:nth-of-type(1)',
      domIndex: 0,
    }],
    microdata: [],
    rdfa: [],
    agent,
  };
}

function runInspect(parsed) {
  const snapshot = snapshotFor(parsed);
  const { entities } = normalize(snapshot);
  const findings = validate(snapshot, entities);
  return { entities, findings, score: score(findings, entities) };
}

function hasCode(result, code) {
  return result.findings.some((finding) => finding.code === code);
}

// Deprecated FAQ
const faq = runInspect({
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [{
    '@type': 'Question',
    name: 'Question?',
    acceptedAnswer: { '@type': 'Answer', text: 'Answer.' },
  }],
});
assert(hasCode(faq, 'FAQ_GOOGLE_UNSUPPORTED'));
assert.equal(faq.findings.filter((f) => f.severity !== 'info').length, 0);
assert.equal(faq.score.total, score([], faq.entities).total);

// Deprecated Sitelinks Searchbox
const website = runInspect({
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  potentialAction: { '@type': 'SearchAction' },
});
assert(hasCode(website, 'SEARCH_ACTION_GOOGLE_UNSUPPORTED'));
assert(!hasCode(website, 'WEBSITE_MISSING_SEARCH_ACTION'));

// Deprecated HowTo
const howTo = runInspect({ '@context': 'https://schema.org', '@type': 'HowTo', name: 'Task' });
assert(hasCode(howTo, 'HOWTO_GOOGLE_UNSUPPORTED'));
assert.equal(howTo.findings.find((f) => f.code === 'HOWTO_GOOGLE_UNSUPPORTED')?.severity, 'info');

// Profile Page
const profile = runInspect({
  '@context': 'https://schema.org',
  '@type': 'ProfilePage',
  mainEntity: { '@type': 'Person' },
});
assert(hasCode(profile, 'PROFILE_MISSING_IDENTITY'));

// Discussion Forum
const forum = runInspect({
  '@context': 'https://schema.org',
  '@type': 'DiscussionForumPosting',
  author: { '@type': 'Person', name: 'A. Person' },
  datePublished: '2026-08-26T12:00:00Z',
  image: 'https://example.test/image.jpg',
});
assert(!hasCode(forum, 'FORUM_MISSING_CONTENT'));

// Return Policy
const finiteReturnPolicy = runInspect({
  '@context': 'https://schema.org',
  '@type': 'MerchantReturnPolicy',
  applicableCountry: 'US',
  returnPolicyCategory: 'https://schema.org/MerchantReturnFiniteReturnWindow',
});
assert(hasCode(finiteReturnPolicy, 'RETURN_POLICY_MISSING_DAYS'));

// Invalid Date
const invalidDate = runInspect({
  '@context': 'https://schema.org',
  '@type': 'Article',
  headline: 'Invalid calendar date',
  datePublished: '2026-02-30',
});
assert(hasCode(invalidDate, 'INVALID_DATE'));
assert.equal(isIso8601Date('2026-01-01T12:00:00+99:99'), false);
assert.equal(isIso4217Currency('ZZZ'), false);

// Robots meta validations
const noindexSnapshot = {
  url: 'https://example.test/noindex',
  title: 'Noindex Page',
  canonical: null,
  robots: 'noindex, nofollow',
  inspectedAt: '',
  jsonld: [],
  microdata: [],
  rdfa: [],
};
const noindexFindings = validate(noindexSnapshot, []);
assert(noindexFindings.some((f) => f.code === 'ROBOTS_NOINDEX'), 'Must detect ROBOTS_NOINDEX');

const nosnippetSnapshot = {
  url: 'https://example.test/nosnippet',
  title: 'Nosnippet Page',
  canonical: null,
  robots: 'nosnippet, max-snippet:0',
  inspectedAt: '',
  jsonld: [],
  microdata: [],
  rdfa: [],
};
const nosnippetFindings = validate(nosnippetSnapshot, []);
assert(nosnippetFindings.some((f) => f.code === 'ROBOTS_NOSNIPPET'), 'Must detect ROBOTS_NOSNIPPET');

// Current Google feature requirements and nested markup normalization
const course = runInspect({ '@context': 'https://schema.org', '@type': 'Course', name: 'Course', description: 'Description' });
assert(!hasCode(course, 'MISSING_PROVIDER'));
const incompleteCourse = runInspect({ '@context': 'https://schema.org', '@type': 'Course', name: 'Course' });
assert(hasCode(incompleteCourse, 'MISSING_DESCRIPTION'));
assert(hasCode(runInspect({ '@context': 'https://schema.org', '@type': 'Recipe', name: 'Soup' }), 'MISSING_IMAGE'));
assert(hasCode(runInspect({ '@context': 'https://schema.org', '@type': 'Dataset', name: 'Data' }), 'MISSING_DESCRIPTION'));
const software = runInspect({ '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'App' });
assert(hasCode(software, 'MISSING_OFFERS_PRICE'));
assert(hasCode(software, 'MISSING_AGGREGATERATING_OR_REVIEW'));
assert(hasCode(runInspect({ '@context': 'https://schema.org', '@type': 'Restaurant', name: 'Cafe' }), 'MISSING_ADDRESS'));
assert(hasCode(runInspect({
  '@context': 'https://schema.org',
  '@type': 'ProfilePage',
  mainEntity: { '@type': 'Product', name: 'Not a profile' },
}), 'PROFILE_INVALID_MAIN_ENTITY'));
const breadcrumb = runInspect({
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://example.test/' },
    { '@type': 'ListItem', position: 2, name: 'Current' },
  ],
});
assert(!hasCode(breadcrumb, 'BREADCRUMB_MISSING_ITEM'));

const videoWithoutDescription = runInspect({
  '@context': 'https://schema.org',
  '@type': 'VideoObject',
  name: 'Video',
  thumbnailUrl: 'https://example.test/video.jpg',
  uploadDate: '2026-08-26',
});
assert(!hasCode(videoWithoutDescription, 'MISSING_DESCRIPTION'));
assert(hasCode(runInspect({ '@context': 'https://schema.org', '@type': 'Product', name: 'Product' }), 'MISSING_OFFERS_OR_REVIEW_OR_AGGREGATERATING'));
for (const signal of ['offers', 'review', 'aggregateRating']) {
  const value = signal === 'aggregateRating'
    ? { '@type': 'AggregateRating', ratingValue: 5, ratingCount: 1 }
    : { '@type': signal === 'offers' ? 'Offer' : 'Review', name: 'Signal' };
  const product = runInspect({ '@context': 'https://schema.org', '@type': 'Product', name: 'Product', [signal]: value });
  assert(!hasCode(product, 'MISSING_OFFERS_OR_REVIEW_OR_AGGREGATERATING'));
}

const eventWithoutAddress = runInspect({
  '@context': 'https://schema.org', '@type': 'Event', name: 'Event', startDate: '2026-09-01',
  location: { '@type': 'Place', name: 'Venue' },
});
assert(hasCode(eventWithoutAddress, 'MISSING_LOCATION_ADDRESS'));

const remoteJob = runInspect({
  '@context': 'https://schema.org', '@type': 'JobPosting', title: 'Engineer', description: 'Build things', datePosted: '2026-08-26',
  hiringOrganization: { '@type': 'Organization', name: 'Example' },
  applicantLocationRequirements: { '@type': 'Country', name: 'US' }, jobLocationType: 'TELECOMMUTE',
});
assert(!hasCode(remoteJob, 'MISSING_JOBLOCATION_OR_APPLICANTLOCATIONREQUIREMENTS'));
assert(hasCode(runInspect({
  '@context': 'https://schema.org', '@type': 'JobPosting', title: 'Engineer', description: 'Build things', datePosted: '2026-08-26',
  hiringOrganization: { '@type': 'Organization', name: 'Example' },
}), 'MISSING_JOBLOCATION_OR_APPLICANTLOCATIONREQUIREMENTS'));

const shortBreadcrumb = runInspect({
  '@context': 'https://schema.org', '@type': 'BreadcrumbList',
  itemListElement: [{ '@type': 'ListItem', item: { '@id': 'https://example.test/', name: 'Home' } }],
});
assert.equal(shortBreadcrumb.findings.find((finding) => finding.code === 'BREADCRUMB_TOO_SHORT')?.severity, 'error');
assert.equal(shortBreadcrumb.findings.find((finding) => finding.code === 'BREADCRUMB_MISSING_POSITION')?.severity, 'error');
assert(!hasCode(shortBreadcrumb, 'BREADCRUMB_MISSING_NAME'));
assert(hasCode(runInspect({
  '@context': 'https://schema.org', '@type': 'BreadcrumbList',
  itemListElement: [
    { position: 1, name: 'Home', item: 'https://example.test/' },
    { '@type': 'ListItem', position: 2, name: 'Current' },
  ],
}), 'BREADCRUMB_INVALID_LIST_ITEM'));

const validQa = runInspect({
  '@context': 'https://schema.org', '@type': 'QAPage',
  mainEntity: {
    '@type': 'Question', name: 'Question?', answerCount: 1,
    acceptedAnswer: { '@type': 'Answer', text: 'Answer.' },
  },
});
assert(!validQa.findings.some((finding) => finding.code.startsWith('QA_')));
const invalidQa = runInspect({
  '@context': 'https://schema.org', '@type': 'QAPage',
  mainEntity: { '@type': 'Question', name: 'Question?', acceptedAnswer: { '@type': 'Answer' } },
});
assert(hasCode(invalidQa, 'QA_MISSING_ANSWER_COUNT'));
assert(hasCode(invalidQa, 'QA_ANSWER_MISSING_TEXT'));
const referencedQa = runInspect({
  '@context': 'https://schema.org',
  '@graph': [
    { '@type': 'QAPage', mainEntity: { '@id': '#question' } },
    { '@id': '#question', '@type': 'Question', name: 'Question?', answerCount: 1, acceptedAnswer: { '@id': '#answer' } },
    { '@id': '#answer', '@type': 'Answer', text: 'Answer.' },
  ],
});
assert(!referencedQa.findings.some((finding) => finding.code.startsWith('QA_')));

const validCarousel = runInspect({
  '@context': 'https://schema.org', '@type': 'ItemList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, url: 'https://example.test/one' },
    { '@type': 'ListItem', position: 2, url: 'https://example.test/two' },
  ],
});
assert(!validCarousel.findings.some((finding) => finding.code.startsWith('CAROUSEL_')));
const mixedCarousel = runInspect({
  '@context': 'https://schema.org', '@type': 'ItemList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, item: { '@type': 'Recipe', name: 'One', url: 'https://example.test/#one' } },
    { '@type': 'ListItem', position: 2, item: { '@type': 'Course', name: 'Two', url: 'https://example.test/#two' } },
  ],
});
assert(hasCode(mixedCarousel, 'CAROUSEL_MIXED_ITEM_TYPES'));
const coTypedCarousel = runInspect({
  '@context': 'https://schema.org', '@type': 'ItemList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, item: { '@type': ['Restaurant', 'LocalBusiness'], name: 'One', url: 'https://example.test/#one' } },
    { '@type': 'ListItem', position: 2, item: { '@type': 'Restaurant', name: 'Two', url: 'https://example.test/#two' } },
  ],
});
assert(!hasCode(coTypedCarousel, 'CAROUSEL_MIXED_ITEM_TYPES'));
assert(!hasCode(coTypedCarousel, 'CAROUSEL_UNSUPPORTED_ITEM_TYPE'));
assert(hasCode(runInspect({
  '@context': 'https://schema.org', '@type': 'ItemList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, item: { '@type': 'Book', name: 'One', url: 'https://example.test/#one' } },
    { '@type': 'ListItem', position: 2, item: { '@type': 'Book', name: 'Two', url: 'https://example.test/#two' } },
  ],
}), 'CAROUSEL_UNSUPPORTED_ITEM_TYPE'));
assert(hasCode(runInspect({
  '@context': 'https://schema.org', '@type': 'ItemList',
  itemListElement: [{ '@type': 'ListItem', position: 1, url: 'https://example.test/one' }],
}), 'CAROUSEL_TOO_SHORT'));

assert(hasCode(runInspect({
  '@context': 'https://schema.org', '@type': 'ProductGroup', name: 'Group',
  hasVariant: [{ '@type': 'Product', name: 'Variant' }],
}), 'PRODUCT_GROUP_MISSING_ID'));
assert(!hasCode(runInspect({
  '@context': 'https://schema.org', '@type': 'ProductGroup', name: 'Group', productGroupID: 'GROUP-1',
  hasVariant: [{ '@type': 'Product', name: 'Variant' }],
}), 'PRODUCT_GROUP_MISSING_ID'));

assert(hasCode(runInspect({
  '@context': 'https://schema.org', '@type': 'Product', name: 'Product',
  aggregateRating: { '@type': 'AggregateRating', ratingValue: 5 },
}), 'RATING_MISSING_COUNT'));
for (const type of ['MiddleSchool', 'Preschool', 'TouristAttraction']) {
  assert(!hasCode(runInspect({ '@context': 'https://schema.org', '@type': type, name: type }), 'MISSING_ADDRESS'));
}

const referencedReview = runInspect({
  '@context': 'https://schema.org',
  '@graph': [
    { '@id': '#review', '@type': 'Review', itemReviewed: { '@id': '#product' }, reviewRating: { '@type': 'Rating', ratingValue: 5 }, author: { '@id': '#author' } },
    { '@id': '#product', '@type': 'Product', name: 'Product', offers: { '@type': 'Offer', price: 10 } },
    { '@id': '#author', '@type': 'Person', name: 'Author' },
  ],
});
assert(!hasCode(referencedReview, 'MISSING_ITEMREVIEWED_NAME'));
assert(!hasCode(referencedReview, 'MISSING_AUTHOR_NAME'));
const nestedReview = runInspect({
  '@context': 'https://schema.org',
  '@graph': [
    { '@id': '#product', '@type': 'Product', name: 'Product', review: { '@id': '#review' } },
    { '@id': '#review', '@type': 'Review', reviewRating: { '@type': 'Rating', ratingValue: 5 }, author: { '@type': 'Person', name: 'Author' } },
  ],
});
assert(!hasCode(nestedReview, 'MISSING_ITEMREVIEWED'), 'Reviews nested through a review property must not require itemReviewed.');
const standaloneReview = runInspect({
  '@context': 'https://schema.org', '@type': 'Review',
  reviewRating: { '@type': 'Rating', ratingValue: 5 }, author: { '@type': 'Person', name: 'Author' },
});
assert(hasCode(standaloneReview, 'MISSING_ITEMREVIEWED'), 'Standalone Reviews must require itemReviewed.');
const referencedProfile = runInspect({
  '@context': 'https://schema.org',
  '@graph': [
    { '@type': 'ProfilePage', mainEntity: { '@id': '#person' } },
    { '@id': '#person', '@type': 'Person', name: 'Author' },
  ],
});
assert(!hasCode(referencedProfile, 'PROFILE_INVALID_MAIN_ENTITY'));
assert(!hasCode(referencedProfile, 'PROFILE_MISSING_IDENTITY'));

const nestedMicrodata = {
  url: 'https://example.test/page', title: 'Example', canonical: null, robots: null, inspectedAt: '',
  jsonld: [],
  microdata: [{
    format: 'microdata', type: 'https://schema.org/BreadcrumbList', selector: 'ol', properties: {
      itemListElement: [
        { format: 'microdata', type: 'https://schema.org/ListItem', selector: 'li:nth-of-type(1)', properties: { name: 'Home', position: '1', item: 'https://example.test/' } },
        { format: 'microdata', type: 'https://schema.org/ListItem', selector: 'li:nth-of-type(2)', properties: { name: 'Current', position: '2' } },
      ],
    },
  }],
  rdfa: [], agent: { hasModelContext: false, modelContext: null, hasLlmsTxtLink: false },
};
const normalizedMicrodata = normalize(nestedMicrodata);
assert.equal(normalizedMicrodata.entities[0].data.itemListElement[0]['@type'], 'ListItem');
assert(!validate(nestedMicrodata, normalizedMicrodata.entities).some((finding) => finding.code.startsWith('BREADCRUMB_MISSING')));

const policy = runInspect({
  '@context': 'https://schema.org', '@type': 'Organization', name: 'Store',
  hasMerchantReturnPolicy: { '@type': 'MerchantReturnPolicy', returnPolicyCategory: 'https://schema.org/MerchantReturnFiniteReturnWindow' },
});
assert(hasCode(policy, 'RETURN_POLICY_MISSING_COUNTRY'));
assert(hasCode(policy, 'RETURN_POLICY_MISSING_DAYS'));

const fragmentIds = runInspect({
  '@context': 'https://schema.org', '@type': 'ProfilePage',
  mainEntity: { '@id': '#author', '@type': 'Person', name: 'Author' },
});
assert(!hasCode(fragmentIds, 'RELATIVE_URL'));

const arbitraryThings = runInspect(Array.from({ length: 5 }, (_, i) => ({
  '@context': 'https://schema.org', '@type': 'Thing', '@id': `https://example.test/#${i}`, a: 1, b: 2, c: 3,
})));
assert.equal(arbitraryThings.score.total, 40);

// Agent Score Invariance
const agentEntities = faq.entities;
const plainScore = score([], agentEntities);
const scoreWithIgnoredAgentArgument = score([], agentEntities, {
  hasModelContext: true,
  modelContext: null,
  hasLlmsTxtLink: true,
});
assert.deepEqual(scoreWithIgnoredAgentArgument, plainScore);
assert.equal(plainScore.breakdown.agent, 0);

// Extract Source String
assert.equal(typeof EXTRACT_SOURCE, 'string');
assert(EXTRACT_SOURCE.includes('JSON.stringify(data)'));
assert(EXTRACT_SOURCE.includes("rel.includes('describedby')"));
assert(!EXTRACT_SOURCE.includes('navigator.modelContext'));
assert(EXTRACT_SOURCE.includes("propEl.querySelectorAll('[typeof]')"), 'RDFa rel wrappers must resolve nested typed values.');
assert(!EXTRACT_SOURCE.includes('properties.vocab = vocab'), 'RDFa vocab declarations must not become entity properties.');
assert(EXTRACT_SOURCE.includes('MAX_MARKUP_PROPERTIES'), 'Markup extraction must cap serialized property counts.');
assert(EXTRACT_SOURCE.includes('MAX_MARKUP_TEXT_CHARS'), 'Markup extraction must cap serialized text and attribute bytes.');

// Manifest Checks
const manifest = JSON.parse(readFileSync(new URL('manifest.json', root), 'utf8'));
assert.equal(manifest.manifest_version, 3);
assert(!('host_permissions' in manifest));
assert(!('permissions' in manifest) || manifest.permissions.length === 0);

// Panel Host Source Checks
const panelSource = readFileSync(new URL('devtools/panel.js', root), 'utf8');
const pageSources = readFileSync(new URL('devtools/page-sources.js', root), 'utf8');
assert(panelSource.includes('setThemeChangeHandler'));
assert(!panelSource.includes('panels.onThemeChanged'));
assert(!panelSource.includes('window.__SCHEMA_DEVTOOLS__ ='));
assert(panelSource.includes('PAGE_WATCH_REMOVE'));
assert(pageSources.includes('containsInteresting'));
assert(pageSources.includes("Symbol.for('schema-devtools.watch')"));
assert(pageSources.includes('attributeOldValue: true'));

let watchObserver;
const watchTimers = [];
const watchWindow = {
  addEventListener() {},
  removeEventListener() {},
};
const watchRoot = {
  nodeType: 1,
  tagName: 'HTML',
  getAttribute() { return null; },
  hasAttribute() { return false; },
  closest() { return null; },
  querySelectorAll() { return []; },
};
class WatchMutationObserver {
  constructor(callback) {
    this.callback = callback;
    watchObserver = this;
  }
  observe(target, options) {
    this.target = target;
    this.options = options;
  }
  disconnect() {}
}
const watchHistory = {
  pushState() {},
  replaceState() {},
};
vm.runInNewContext(PAGE_WATCH_INSTALL, {
  window: watchWindow,
  document: { documentElement: watchRoot },
  history: watchHistory,
  MutationObserver: WatchMutationObserver,
  setTimeout(callback) {
    watchTimers.push(callback);
    return watchTimers.length;
  },
  clearTimeout() {},
});
assert.equal(watchObserver.options.attributeOldValue, true);
watchObserver.callback([{
  type: 'attributes',
  target: watchRoot,
  attributeName: 'typeof',
  oldValue: 'Product',
  addedNodes: [],
  removedNodes: [],
}]);
assert.equal(watchTimers.length, 1, 'Removing the final schema attribute must schedule a live update.');
watchTimers.shift()();
assert.equal(watchWindow[Symbol.for('schema-devtools.watch')].generation, 2);

console.log('✅ Passed');

// -----------------------------------------------------------------------------
// 3. Declarative Rule Catalog & Syntax Audit
// -----------------------------------------------------------------------------
process.stdout.write('⏳ 3. Rule Catalog & Syntax Audit... ');

assert(Array.isArray(RICH_RESULT_RULES) && RICH_RESULT_RULES.length >= 20, 'Catalog must contain 20+ rich result rules.');
for (const rule of RICH_RESULT_RULES) {
  assert(rule.type, `Rule missing type: ${JSON.stringify(rule)}`);
  assert(rule.docsUrl && /^https?:\/\//i.test(rule.docsUrl), `Rule ${rule.type} has invalid docsUrl: ${rule.docsUrl}`);
  assert(Array.isArray(rule.required), `Rule ${rule.type} required must be an array`);
  assert(Array.isArray(rule.recommended), `Rule ${rule.type} recommended must be an array`);
  assert(!rule.anyOf || rule.anyOf.every((alternatives) => Array.isArray(alternatives) && alternatives.length > 0), `Rule ${rule.type} anyOf must contain property-path alternatives`);
}

assert(Array.isArray(DEPRECATED_TYPES) && DEPRECATED_TYPES.length >= 2, 'Must contain deprecated types list.');
assert(FAQ_GOOGLE_STATUS.code && FAQ_GOOGLE_STATUS.docsUrl, 'FAQ status must have code and docsUrl');

assert.equal(typeof matchRuleInCatalog, 'function');
assert.equal(typeof hasProperty, 'function');
assert.equal(typeof hasPropertyPath, 'function');
assert.equal(hasPropertyPath({ offers: [{ price: 0 }] }, 'offers.price'), true);
assert.equal(typeof isIso8601Date, 'function');
assert.equal(typeof isIso4217Currency, 'function');
assert.equal(isIso8601Date('2026-08-26'), true);
assert.equal(isIso8601Date('2026-02-30'), false);
assert.equal(isIso4217Currency('USD'), true);
assert.equal(isIso4217Currency('INVALID'), false);

// Verify all sandbox fixtures
const fixtureKeys = Object.keys(FIXTURES);
assert(fixtureKeys.length >= 15, `Expected 15+ fixtures, got ${fixtureKeys.length}`);
for (const [key, fixture] of Object.entries(FIXTURES)) {
  assert(fixture.name && typeof fixture.name === 'string', `Fixture ${key} missing name`);
  assert(fixture.url && typeof fixture.url === 'string', `Fixture ${key} missing url`);
  assert(Array.isArray(fixture.entities) && fixture.entities.length > 0, `Fixture ${key} has no entities`);

  const jsonldBlocks = fixture.entities.filter((e) => !e.format || e.format === 'jsonld');
  const microdataNodes = fixture.entities.filter((e) => e.format === 'microdata');
  const rdfaNodes = fixture.entities.filter((e) => e.format === 'rdfa');

  const snapshot = {
    url: fixture.url,
    canonical: fixture.canonical || fixture.url,
    jsonld: jsonldBlocks.map((e, index) => ({
      index,
      raw: JSON.stringify(e.data || e),
      parsed: e.data || e,
      parseError: null,
      selector: `jsonld:${index}`,
    })),
    microdata: microdataNodes.map((e, index) => ({
      format: 'microdata',
      type: e.types || ['Thing'],
      properties: e.data || {},
      selector: `div[itemscope]:nth-of-type(${index + 1})`,
    })),
    rdfa: rdfaNodes.map((e, index) => ({
      format: 'rdfa',
      type: e.types || ['Thing'],
      properties: e.data || {},
      selector: `div[typeof]:nth-of-type(${index + 1})`,
    })),
  };

  const { entities } = normalize(snapshot);
  assert(entities.length > 0, `Fixture ${key} normalized 0 entities`);
  const findings = validate(snapshot, entities);
  const q = score(findings, entities);
  assert(typeof q.total === 'number' && q.total >= 0 && q.total <= 100, `Fixture ${key} produced invalid score`);

  if (key === 'errors') {
    assert(q.errorCount > 0, 'Errors fixture must trigger at least 1 error finding');
  }
}

console.log(`✅ Passed (${RICH_RESULT_RULES.length} active rich-result rules, ${DEPRECATED_TYPES.length} deprecations, ${fixtureKeys.length} fixtures)`);

// -----------------------------------------------------------------------------
// 4. VanJS Modular UI & DevTools Host Smoke Tests
// -----------------------------------------------------------------------------
process.stdout.write('⏳ 4. VanJS Panel & Sidebar UI Checks... ');

const panelJs = readFileSync(new URL('devtools/panel.js', root), 'utf8');
const panelApp = readFileSync(new URL('ui/app.js', root), 'utf8');
const coreStore = readFileSync(new URL('ui/store.js', root), 'utf8');
const toolbarJs = readFileSync(new URL('ui/components/toolbar.js', root), 'utf8');
const entityListJs = readFileSync(new URL('ui/components/entity-list.js', root), 'utf8');
const panelHtml = readFileSync(new URL('devtools/panel.html', root), 'utf8');
const themeCss = readFileSync(new URL('ui/theme.css', root), 'utf8');
const vanJs = readFileSync(new URL('vendor/van.js', root), 'utf8');
const vanXJs = readFileSync(new URL('vendor/van-x.js', root), 'utf8');

const sidebarHostJs = readFileSync(new URL('devtools/sidebar.js', root), 'utf8');
const selectionExtractJs = readFileSync(new URL('src/extract-selection.js', root), 'utf8');
const sidebarHtml = readFileSync(new URL('devtools/sidebar.html', root), 'utf8');
const sidebarViewJs = readFileSync(new URL('ui/sidebar-view.js', root), 'utf8');

assert.match(panelHtml, /type="module" src="panel.js"/, 'Panel must load as an ES module.');
assert.match(panelHtml, /href="\.\.\/ui\/panel\.css"/, 'Panel HTML must link ../ui/panel.css.');
assert.match(sidebarHtml, /href="\.\.\/ui\/sidebar\.css"/, 'Sidebar HTML must link ../ui/sidebar.css.');
assert.match(sidebarHostJs, /from '\.\.\/ui\/sidebar-view\.js'/, 'Sidebar host must import ../ui/sidebar-view.js.');
assert.match(selectionExtractJs, /hasRdfaRelation/, 'Sidebar RDFa source indexing must match nested relation extraction.');
assert.match(sidebarHostJs, /engine\.SELECTION_EXTRACT_SOURCE/, 'Sidebar must use the shared selected-node extraction source.');
assert.match(sidebarHostJs, /candidate\.types\.some/, 'Sidebar must prefer properties from the normalized selected entity.');
assert.match(sidebarHostJs, /ensureFindings\(true\)/, 'Sidebar selections must refresh findings after page mutations.');
assert.match(panelApp, /from '\.\.\/vendor\/van\.js'/, 'Panel UI must use the vendored VanJS runtime.');
assert.match(panelApp, /van\.tags/, 'Panel UI must use VanJS tag functions.');
assert.match(panelApp, /import\('\.\/views\/lazy\.js'\)/, 'Optional panel views must load through a dynamic import.');
assert.doesNotMatch(panelApp, /from '\.\/views\/(?:raw|graph|findings|serp)\.js'/, 'Optional views must not be eager imports.');
assert.doesNotMatch(coreStore, /function serpCards/, 'SERP generation must stay out of the eager core store.');
assert.doesNotMatch(coreStore, /function buildEntityGraph/, 'Graph generation must stay out of the eager core store.');
assert.match(sidebarViewJs, /van\.tags/, 'Sidebar view must use VanJS tag functions.');
assert.doesNotMatch(panelApp, /\.innerHTML/, 'Panel components must not assign innerHTML.');
assert.doesNotMatch(sidebarViewJs, /\.innerHTML/, 'Sidebar view must not assign innerHTML.');
assert.match(vanJs, /tags:/, 'Vendored VanJS must be self-contained in the extension.');
assert.match(vanXJs, /reactive/, 'Vendored VanX must be self-contained in the extension.');
assert.match(themeCss, /--sys-color-base/, 'Shared theme tokens must include DevTools system colors.');
assert.match(
  panelJs,
  /function selectEntity\(entity, \{ inspect = false, highlight = true \} = \{\}\)/,
  'Entity selection must stay on the Schema tab; inspect() switches DevTools panels.',
);
assert.match(toolbarJs, /id:\s*['"]btn-inspect['"]/, 'Inspect in Elements must remain an explicit action in toolbar.');
assert.match(toolbarJs, /actions\.inspectSelected\(\)/, 'Inspect in Elements must be wired to the explicit button.');
assert.match(
  entityListJs,
  /actions\.selectEntity\(entity,\s*\{\s*inspect:\s*event\.altKey\s*\}\)/,
  'Ordinary entity clicks may inspect only when Alt is held.',
);
assert.doesNotMatch(panelApp, /\.innerHTML/, 'Panel templates must not assign innerHTML.');
assert.doesNotMatch(toolbarJs, /\.innerHTML/, 'Toolbar must not assign innerHTML.');
assert.doesNotMatch(entityListJs, /\.innerHTML/, 'Entity list must not assign innerHTML.');
assert.doesNotMatch(panelJs, /\.innerHTML/, 'Panel analysis must not assign innerHTML.');
const compareSource = readFileSync(new URL('scripts/compare.mjs', root), 'utf8');
assert.doesNotMatch(compareSource, /Highly Consistent/, 'Validator comparison must not infer semantic parity from error counts.');
assert.match(compareSource, /Type alignment:/, 'Validator comparison must report type alignment independently.');
assert.doesNotMatch(readFileSync(new URL('ui/views/serp.js', root), 'utf8'), /src:\s*card\.image/, 'SERP previews must not request inspected-page images.');
assert.match(panelJs, /listen\(chrome\.devtools\?\.network\?\.onNavigated/, 'Navigation refresh must not assume network.onNavigated exists.');
assert.match(panelJs, /formatEvalException/, 'Eval failures must format Chrome exceptionInfo.');

const hostJs = readFileSync(new URL('devtools/host.js', root), 'utf8');
assert.match(hostJs, /details/, 'Eval errors must substitute exceptionInfo.details into description templates.');
assert.match(hostJs, /function listen/, 'Optional Chrome events must be feature-detected before addListener.');

const inspectCalls = [...panelJs.matchAll(/\binspect\(/g)];
assert.equal(inspectCalls.length, 3, 'inspect() must stay limited to inspectExprForEntity.');

const allUi = `${panelJs}\n${panelApp}\n${toolbarJs}\n${entityListJs}`;
const clickSelects = [...allUi.matchAll(/selectEntity\([^)]*\)/g)].map((match) => match[0]);
assert.ok(
  clickSelects.every((call) => !call.includes('inspect: true')),
  'No in-panel click path may hardcode inspect: true.',
);

store.entities = [
  { id: 'entity:1', types: ['Article'], format: 'jsonld', sourceIndex: 0, data: { headline: 'Hello' } },
  { id: 'entity:2', types: ['ImageObject'], format: 'jsonld', sourceIndex: 0, data: { url: 'https://example.com/a.jpg' } },
];
store.query = 'imageobject';
assert.equal(visibleEntities().map((entity) => entity.id).join(','), 'entity:2');
assert.equal(matchesSearch('Article jsonld', 'article'), true);
assert.equal(matchesSearch('Article jsonld', 'product'), false);
store.entities = [
  { id: 'restaurant:1', types: ['Restaurant'], format: 'jsonld', sourceIndex: 0, data: { name: 'Cafe' } },
  { id: 'review:1', types: ['Review'], format: 'jsonld', sourceIndex: 0, data: { name: 'Superb', reviewRating: { ratingValue: '5' } } },
  { id: 'video:1', types: ['VideoObject'], format: 'jsonld', sourceIndex: 0, data: { name: 'Tutorial', duration: 'PT10M' } },
];
const cards = serpCards();
assert.equal(cards.length, 3, 'Must generate cards for Restaurant, Review, and Video.');
assert(cards.some((c) => c.kind === 'Review'), 'Review SERP card must be generated.');
assert(cards.some((c) => c.kind === 'Video'), 'Video SERP card must be generated.');

assert.equal(
  formatEvalException({ description: 'Operation failed: %s', details: ['Inspected tab was closed'] }),
  'Operation failed: Inspected tab was closed',
);
assert.equal(formatEvalException({ description: 'Operation failed: %s' }), 'Evaluation failed');
assert.equal(formatEvalException({ isException: true, value: 'page threw' }), 'page threw');
assert.equal(listen(undefined, () => {}), false);
let listened = 0;
assert.equal(listen({ addListener: (handler) => handler() }, () => { listened += 1; }), true);
assert.equal(listened, 1);

console.log('✅ Passed');

// -----------------------------------------------------------------------------
// 5. Security & Dependency Guardrails
// -----------------------------------------------------------------------------
process.stdout.write('⏳ 5. Security & Dependency Guardrails... ');

const agentsCheck = spawnSync('git', ['grep', '\\.agents', '--', ':!.agents', ':!*.md', ':!.cursor', ':!.gitignore', ':!scripts/test.mjs'], { encoding: 'utf8' });
assert.equal(agentsCheck.stdout.trim(), '', 'No production files may reference .agents/');

const usersCheck = spawnSync('git', ['grep', '-i', '/Users/', '--', ':!*.lock', ':!node_modules', ':!scripts/test.mjs'], { encoding: 'utf8' });
assert.equal(usersCheck.stdout.trim(), '', 'No private local paths (/Users/) allowed.');

console.log('✅ Passed');

console.log('\n🎉 All test suites and security guardrails passed cleanly!\n');
