/**
 * Agent-friendly bundle export.
 * @file
 */

/** @typedef {import('./types.js').PageSnapshot} PageSnapshot */
/** @typedef {import('./types.js').Entity} Entity */
/** @typedef {import('./types.js').Finding} Finding */
/** @typedef {import('./types.js').ScoreResult} ScoreResult */
/** @typedef {import('./types.js').AgentBundle} AgentBundle */

/**
 * @param {object} input
 * @param {PageSnapshot} input.snapshot
 * @param {Entity[]} input.entities
 * @param {Finding[]} input.findings
 * @param {ScoreResult} input.score
 * @returns {AgentBundle}
 */
export function buildAgentBundle({ snapshot, entities, findings, score: scoreResult }) {
  const errors = findings.filter((f) => f.severity === 'error').length;
  const warnings = findings.filter((f) => f.severity === 'warning').length;

  return {
    version: 1,
    tool: 'schema-devtools',
    url: snapshot.url,
    title: snapshot.title,
    canonical: snapshot.canonical,
    inspectedAt: snapshot.inspectedAt,
    score: scoreResult,
    summary: {
      jsonld: snapshot.jsonld.length,
      microdata: snapshot.microdata.length,
      rdfa: snapshot.rdfa.length,
      entities: entities.length,
      errors,
      warnings,
    },
    entities,
    findings,
    agent: snapshot.agent,
  };
}

/**
 * @param {Finding[]} findings
 * @param {number} limit
 * @returns {string}
 */
function formatFindings(findings, limit) {
  if (findings.length === 0) return 'None';
  return findings.slice(0, limit).map((f) => {
    const prefix = f.severity === 'error' ? '❌' : f.severity === 'warning' ? '⚠️' : 'ℹ️';
    const loc = f.path ? ` (${f.path})` : '';
    return `${prefix} ${f.code}${loc}: ${f.message}`;
  }).join('\n');
}

/**
 * @param {Entity[]} entities
 * @param {number} limit
 * @returns {string}
 */
function formatEntities(entities, limit) {
  if (entities.length === 0) return 'None';
  return entities.slice(0, limit).map((e) => {
    const types = e.types.length ? e.types.join(', ') : 'Untyped';
    return `- ${types} [${e.format}] @ ${e.path}`;
  }).join('\n');
}

/**
 * Convert agent bundle to markdown for LLM paste.
 * @param {AgentBundle} bundle
 * @returns {string}
 */
export function toAgentMarkdown(bundle) {
  const lines = [
    '# Schema DevTools Report',
    '',
    `**URL:** ${bundle.url}`,
    `**Title:** ${bundle.title}`,
    bundle.canonical ? `**Canonical:** ${bundle.canonical}` : null,
    `**Inspected:** ${bundle.inspectedAt}`,
    '',
    `## Score: ${bundle.score.total}/100 (${bundle.score.label})`,
    '',
    `- Errors: ${bundle.summary.errors}`,
    `- Warnings: ${bundle.summary.warnings}`,
    `- JSON-LD blocks: ${bundle.summary.jsonld}`,
    `- Microdata items: ${bundle.summary.microdata}`,
    `- RDFa items: ${bundle.summary.rdfa}`,
    `- Entities: ${bundle.summary.entities}`,
    '',
    '## Entities',
    formatEntities(bundle.entities, 20),
    bundle.entities.length > 20 ? `\n… and ${bundle.entities.length - 20} more` : null,
    '',
    '## Findings (top)',
    formatFindings(
      bundle.findings.filter((f) => f.severity === 'error'),
      10,
    ),
    '',
    '### Warnings',
    formatFindings(
      bundle.findings.filter((f) => f.severity === 'warning'),
      10,
    ),
    '',
    '## Agent Surface',
    `- Model context: ${bundle.agent.hasModelContext ? 'yes' : 'no'}`,
    `- llms.txt link hint: ${bundle.agent.hasLlmsTxtLink ? 'yes' : 'no'}`,
    '',
    '---',
    '_Generated by Schema DevTools_',
  ];

  return lines.filter((l) => l !== null).join('\n');
}
